BattleMage.Player=JAK.ClassMaker.makeClass({NAME:"BattleMage.Player",VERSION:"1.0",IMPLEMENT:JAK.ISignals});
BattleMage.Player.prototype.$constructor=function(b,c){this.dung=b;this.map=this.dung.getMapInstance();this.mapSize=this.map.getMapSize();this.opt={step:this.dung.opt.step};this.HP=RPG.HP;this.ipadDebug=!1;this.stickImg=new Image;this.stickImg.src="./img/stick.png";this.moving=!1;this.direction=this.dung.direction;this.dom={};this.ec=[];this.sigs=[];this.dom.canvas=c;this.canvas=this.dom.canvas.getContext("2d");this.pxCoords={x:0,y:0};this.coords={x:0,y:0};this.canvasPos=JAK.DOM.getBoxPosition(this.map.getDomCanvas());
this.canvasSize={width:this.map.getDomCanvas().width,height:this.map.getDomCanvas().height};this.img=RPG.STYLE[RPG.YOU].img;this.SPRITE={img:this.img,step:30,steps:3,interval:150,scale:1,start:(new Date).getTime()};this.SPRITE[RPG.N]={top:96,height:32};this.SPRITE[RPG.W]={top:32,height:32};this.SPRITE[RPG.E]={top:64,height:32};this.SPRITE[RPG.S]={top:0,height:32};this.startTime=(new Date).getTime();this.sprite=new Sprite(this.canvas,this.img,this.SPRITE);this.attack=new BattleMage.Attack(this);this._link()};
BattleMage.Player.prototype._dmg=function(b){this.HP=0>this.HP-b.data.dmg?0:this.HP-b.data.dmg;0>=this.HP&&this._death();this.makeHPBar()};BattleMage.Player.prototype._death=function(){this.deathImg=new Image;this.deathImg.src="./img/skull.jpg";this.dead=!0};
BattleMage.Player.prototype._drawDeath=function(){this.deathIteration=0<=this.deathIteration?this.deathIteration+1:0;20<=this.deathIteration&&(this.deathIteration=20);var b=this.mapSize.w/(20-this.deathIteration),c=this.mapSize.h/(20-this.deathIteration);this.canvas.drawImage(this.deathImg,0,0,b>=this.mapSize.w?this.mapSize.w:b,c>=this.mapSize.h?this.mapSize.h:c)};
BattleMage.Player.prototype.makeHPBar=function(){this.canvas.fillStyle="rgba(204, 0, 0, 0.3)";this.canvas.fillRect(this.mapSize.w-100,0,100,18);this.canvas.fillStyle="rgba(0, 204, 0, 0.3)";this.canvas.fillRect(this.mapSize.w-100,0,this.HP/(RPG.HP/100),18)};BattleMage.Player.prototype.setCenter=function(b){this.pxCoords=b};
BattleMage.Player.prototype.draw=function(){if(this.dead)this._drawDeath();else{this.attacking&&this.attack.draw();var b=this.SPRITE.img;if(this.moving)this.sprite.direction=this.direction,this.sprite.draw({x:this.left,y:this.top});else{var c=this.SPRITE[this.direction].height;this.canvas.drawImage(b,0,this.SPRITE[this.direction].top,this.SPRITE.step,c,this.left,this.top,this.SPRITE.step*this.SPRITE.scale,c*this.SPRITE.scale)}this.makeHPBar();("iPad"==JAK.Browser._platform||this.ipadDebug)&&this._stickDraw()}};
BattleMage.Player.prototype._stickDraw=function(){this.stickCanvas.clearRect(0,0,this.stickCanvasSize.w,this.stickCanvasSize.h);var b=this.stick;this.stickCanvas.save();this.stickCanvas.drawImage(this.stickImg,0,0,88,88,b.limit.x-this.stickLimitSize/2,b.limit.y-this.stickLimitSize/2,this.stickLimitSize,this.stickLimitSize);this.stickCanvas.drawImage(this.stickImg,89,14,60,60,b.input.x-30,b.input.y-30,60,60);this.stickCanvas.restore()};
BattleMage.Player.prototype.update=function(){this.attacking&&this.attack.update();if("iPad"==JAK.Browser._platform||this.ipadDebug)var b=this._stickUpdate();else{var b=(new Date).getTime(),c=(b-this.startTime)/1E3;this.startTime=b;b={x:this.pxCoords.x,y:this.pxCoords.y};if(this.moveLeft||this.moveRight||this.moveTop||this.moveBottom)if(this.moving=!0,this.moveLeft&&(this.direction=RPG.W,b.x+=Math.floor(-this.opt.step*c)),this.moveRight&&(this.direction=RPG.E,b.x+=Math.floor(this.opt.step*c)),this.moveTop&&
(this.direction=RPG.N,b.y+=Math.floor(-this.opt.step*c)),this.moveBottom)this.direction=RPG.S,b.y+=Math.floor(this.opt.step*c)}this._finder(this.map.getCoords(b))?(this.pxCoords.x=b.x,this.pxCoords.y=b.y,c=this.dung.opt.allMap?{x:0,y:0}:this.map._smallCorner(),this.left=this.pxCoords.x-c.x-this.SPRITE.step/2,this.top=this.pxCoords.y-c.y-this.SPRITE[this.direction].height/2):this.moving=!1};
BattleMage.Player.prototype._stickUpdate=function(){this.stick.update();var b=(new Date).getTime(),c=(b-this.startTime)/1E3;this.startTime=b;b={x:this.pxCoords.x,y:this.pxCoords.y};if(this.stick.active&&4<this.stick.length){this.moving=!0;var d=this.stick.length*this.stick.normal.x,f=this.stick.length*this.stick.normal.y;d>this.stickInputSize/2?(this.moveRight=!0,this.direction=RPG.E,b.x+=Math.floor(this.opt.step*c)):d<-1*(this.stickInputSize/2)&&(this.moveLeft=!0,this.direction=RPG.W,b.x+=Math.floor(-this.opt.step*
c));f>this.stickInputSize/2?(this.moveBottom=!0,this.direction=RPG.S,b.y+=Math.floor(this.opt.step*c)):f<-1*(this.stickInputSize/2)&&(this.moveTop=!0,this.direction=RPG.N,b.y+=Math.floor(-this.opt.step*c))}return b};BattleMage.Player.prototype.getPosition=function(){return{x:this.left,y:this.top}};BattleMage.Player.prototype.getDirection=function(){return this.direction};
BattleMage.Player.prototype._finder=function(b){var c=this.map.getMap();if((0<=b[0]||b[0]<c.length)&&(0<=b[1]||b[1]<c[0].length))switch(c[b[0]][b[1]]){case RPG.NONE:return 1;case RPG.WALL:return 0}};
BattleMage.Player.prototype._moveStart=function(b){switch(b.keyCode){case 32:this.attacking=!0;JAK.Events.cancelDef(b);break;case 38:this.moveTop=!0;JAK.Events.cancelDef(b);break;case 40:this.moveBottom=!0;JAK.Events.cancelDef(b);break;case 39:this.moveRight=!0;JAK.Events.cancelDef(b);break;case 37:this.moveLeft=!0,JAK.Events.cancelDef(b)}};
BattleMage.Player.prototype._moveEnd=function(b){switch(b.keyCode){case 32:this.attacking=!1;JAK.Events.cancelDef(b);break;case 39:this.moving=this.moveRight=!1;break;case 37:this.moving=this.moveLeft=!1;break;case 38:this.moving=this.moveTop=!1;case 40:this.moving=this.moveBottom=!1}};BattleMage.Player.prototype.getCoords=function(){return this.map.getCoords(this.pxCoords)};BattleMage.Player.prototype.getPxCoords=function(){return this.pxCoords};
BattleMage.Player.prototype._stickInit=function(){this.stickBuffer=65;this.stickLimitSize=88;this.stickInputSize=10;this.stickCanvasSize={w:1024,h:690};this.stick=new Stick(this.stickInputSize);this.stick.setLimitXY(this.stickCanvasSize.w-2*this.stickLimitSize,this.stickCanvasSize.h-2*this.stickBuffer);this.stick.setInputXY(this.stickCanvasSize.w-2*this.stickLimitSize,this.stickCanvasSize.h-2*this.stickBuffer);this.dom.stickCanvas=JAK.mel("canvas",{className:"stickCanvas"},{position:"absolute",bottom:"0px",
left:"0px",border:"1px solid red",zIndex:"99"});this.dom.stickCanvas.width=this.stickCanvasSize.w;this.dom.stickCanvas.height=this.stickCanvasSize.h;this.stickCanvas=this.dom.stickCanvas.getContext("2d");document.body.appendChild(this.dom.stickCanvas);this.ipadDebug?(this.ec.push(JAK.Events.addListener(this.dom.stickCanvas,"mousedown",this,"_touchStart")),this.ec.push(JAK.Events.addListener(document.body,"mousemove",this,"_touchMove")),this.ec.push(JAK.Events.addListener(document.body,"mouseup",this,
"_touchEnd"))):(this.ec.push(JAK.Events.addListener(this.dom.stickCanvas,"touchstart",this,"_touchStart")),this.ec.push(JAK.Events.addListener(this.dom.stickCanvas,"touchmove",this,"_touchMove")),this.ec.push(JAK.Events.addListener(this.dom.stickCanvas,"touchend",this,"_touchEnd")))};BattleMage.Player.prototype._touchStart=function(b){JAK.Events.cancelDef(b);var c=this.stick;0;b=this.ipadDebug?b:b.touches[0];this.ipadDebug?c.setInputXY(b.layerX,b.layerY):c.setInputXY(b.pageX,b.pageY);c.active=!0};
BattleMage.Player.prototype._touchMove=function(b){JAK.Events.cancelDef(b);if(this.stick.active){var c=this.stick,b=this.ipadDebug?b:b.touches[0];this.ipadDebug?c.setInputXY(b.layerX,b.layerY):c.setInputXY(b.pageX,b.pageY)}};BattleMage.Player.prototype._touchEnd=function(b){JAK.Events.cancelDef(b);this.stick.setInputXY(this.stick.limit.x,this.stick.limit.y);this.stick.active=!1};
BattleMage.Player.prototype._makeAttackButton=function(){this.dom.attackButton=JAK.mel("div",{className:"attackButton"},{position:"absolute",width:"100px",height:"100px",background:"red",bottom:"20px",left:"20px",zIndex:"999"});document.body.appendChild(this.dom.attackButton);this.ec.push(JAK.Events.addListener(this.dom.attackButton,"touchstart",this._touchAttack.bind(this,!0)));this.ec.push(JAK.Events.addListener(this.dom.attackButton,"touchend",this._touchAttack.bind(this,!1)))};
BattleMage.Player.prototype._touchAttack=function(b,c){JAK.Events.cancelDef(c);this.attacking=b||!1};BattleMage.Player.prototype._link=function(){"iPad"==JAK.Browser._platform||this.ipadDebug?(this._stickInit(),this._makeAttackButton()):(this.ec.push(JAK.Events.addListener(window,"keydown",this,"_moveStart")),this.ec.push(JAK.Events.addListener(window,"keyup",this,"_moveEnd")));this.sigs.push(this.addListener("npcAttack",this._dmg.bind(this)))};RPGMAP.ShadowLighting=JAK.ClassMaker.makeClass({VERSION:"1.1",NAME:"RPGMAP.ShadowLighting",EXTEND:RPGMAP});RPGMAP.ShadowLighting.prototype._visibleCoords=function(b,c,d,f){var g=f.length,h=Math.floor(c),k=0,l=0,o=null,p=!1;do{o=h;0>o&&(o+=g);o>=g&&(o-=g);var o=f[o],n=1>o[0]+o[1]+1.0E-4;h<c?(l+=h+1-c,n&&l>o[0]+1.0E-4&&(p=!0,b&&(o[0]=l))):k+1>d?(l=d-k,n&&l>o[1]+1.0E-4&&(p=!0,b&&(o[1]=l))):(l=1,n&&(p=!0,b&&(o[0]=1,o[1]=1)));k+=l;h++}while(k<d);return p};
RPGMAP.ShadowLighting.prototype.getCoordsInCircle=function(b,c,d){for(var f=[],g=this.MAP.length,h=this.MAP[0].length,k=[],l=0;l<b.length;l++)k.push(b[l]);b=[k[0]+c,k[1]+c];k=[0,6,4,2];c*=8;for(l=0;l<c;l++){0>b[0]||0>b[1]||b[0]>=g||b[1]>=h?d&&f.push(null):f.push(b);var o=k[Math.floor(l*k.length/c)],b=[b[0]+RPG.DIR[o][0],b[1]+RPG.DIR[o][1]]}return f};RPGMAP.ShadowLighting.prototype._blocks=function(b){return this.MAP[b[0]][b[1]]==RPG.WALL?!0:!1};
RPGMAP.ShadowLighting.prototype.showShadow=function(){var b=this.radius,c=this.coordsStart,d=!1,f=[],g=[];g.push(this.coordsStart);for(var h=0,k=8*b,l=0;l<k;l++)f.push([0,0]);for(var o=1;o<=b;o++)for(var h=h+8,p=k/h,n=this.getCoordsInCircle(c,o,!0),l=0;l<n.length;l++)if(n[l]){var d=n[l],q=(l-0.5)*p+0.5;this._visibleCoords(this._blocks(d),q,p,f)&&g.push(d);d=!0;for(q=0;q<k;q++)if(1>f[q][0]+f[q][1]+1.0E-4){d=!1;break}if(d)return g}return g};BattleMage.NPC=JAK.ClassMaker.makeClass({NAME:"BattleMage.NPC",VERSION:"1.0",IMPLEMENT:JAK.ISignals});
BattleMage.NPC.prototype.$constructor=function(b,c){this.opt={startPos:{x:0,y:0},canvas:null,stop:!1};for(var d in c)this.opt[d]=c[d];this.dung=b;this.HP=100;this.DMG=5;this.map=this.dung.getMapInstance();this.mapPointSize=this.map.getPointSize();this.interval=500;this.startTime=(new Date).getTime();this.canvas=this.opt.canvas.getContext("2d");this.direction=RPG.E;this.moving=!1;this.pxcoords={x:0,y:0};this.dmgsTexts=[];this.img=RPG.STYLE[RPG.NPC].img;this.SPRITE={img:this.img,step:32,steps:3,interval:150,
scale:1,start:(new Date).getTime()};this.SPRITE[RPG.N]={top:96,height:32};this.SPRITE[RPG.W]={top:32,height:32};this.SPRITE[RPG.E]={top:64,height:32};this.SPRITE[RPG.S]={top:0,height:32};this.sprite=new Sprite(this.canvas,this.img,this.SPRITE);this._makeNPC()};BattleMage.NPC.prototype.$destructor=function(){this.death=!0};BattleMage.NPC.prototype._pxPos=function(b){return{x:b[1]*this.mapPointSize.w,y:b[0]*this.mapPointSize.h}};
BattleMage.NPC.prototype.update=function(){this.opt.stop&&(this.moving=!1);var b=this.startTime+this.interval,c=(new Date).getTime();this.moving?this._moveAnim(((new Date).getTime()-this.moveTime)/this.interval%1):c>b&&(this._move(),this.startTime=c);this._updateDmg()};
BattleMage.NPC.prototype._moveAnim=function(b){var c={x:0,y:0};this.dung.opt.allMap||(c=this.map._smallCorner());var d=this._pxPos(this.coords),f=this.left,g=this.top,f=(d.x-f)*b+f,d=(d.y-g)*b+g;this.smallPxCoords={x:f,y:d};this.left=f;this.top=d;this.smallPxCoords={x:f-c.x,y:d-c.y};0.95<b&&(this.moving=!1)};BattleMage.NPC.prototype.draw=function(){for(var b=this.map.showShadow(),c=0;c<b.length;c++)if(this.coords[0]==b[c][0]&&this.coords[1]==b[c][1]){this._draw();break}};
BattleMage.NPC.prototype._draw=function(){var b=this.SPRITE.img;if(this.dung.opt.allMap)var c=this.left,d=this.top;else c=this.smallPxCoords.x,d=this.smallPxCoords.y;if(this.moving)this.sprite.direction=this.direction,this.sprite.draw({x:c,y:d});else{var f=this.SPRITE[this.direction].height;this.canvas.drawImage(b,0,this.SPRITE[this.direction].top,this.SPRITE.step,f,c,d,this.SPRITE.step*this.SPRITE.scale,f*this.SPRITE.scale)}this._drawDmg()};
BattleMage.NPC.prototype.hasCoords=function(b){return""+this.coords==""+b?this:0};BattleMage.NPC.prototype.getCoords=function(){return this.coords};BattleMage.NPC.prototype.getSmallPxCoords=function(){return this.smallPxCoords};BattleMage.NPC.prototype.getSmallMiddleCoords=function(){return{x:this.smallPxCoords.x+this.SPRITE.step*this.SPRITE.scale/2,y:this.smallPxCoords.y+this.SPRITE[this.direction].height*this.SPRITE.scale/2}};
BattleMage.NPC.prototype.getDmg=function(b){this.HP-=b;if(0>=this.HP)return this._die(),!0;this._showDmg(b);return!1};BattleMage.NPC.prototype._die=function(){this.$destructor()};BattleMage.NPC.prototype._showDmg=function(b){this.dmgsTexts.push({dmg:b,coords:{x:this.smallPxCoords.x,y:this.smallPxCoords.y},iteration:0})};
BattleMage.NPC.prototype._updateDmg=function(){for(var b=[],c=0;c<this.dmgsTexts.length;c++){var d=this.dmgsTexts[c];20<=d.iteration&&b.push(c);d.coords.y-=2;d.iteration+=1}for(c=0;c<b.length;c++)this.dmgsTexts.splice(b[c],1)};BattleMage.NPC.prototype._drawDmg=function(){for(var b=0;b<this.dmgsTexts.length;b++){var c=this.dmgsTexts[b];this.canvas.font="normal 24px Arial";this.canvas.fillStyle="red";this.canvas.fillText(c.dmg,c.coords.x,c.coords.y)}};
BattleMage.NPC.prototype._makeNPC=function(){if(0==this.opt.startPos.x||0==this.opt.startPos.y)var b=this.map._randRange(0,this.map.MAP.length-1),c=this.map._randRange(0,this.map.MAP[0].length-1);else b=this.opt.startPos.x,c=this.opt.startPos.y;this.coords=[b,c];this.left=this.mapPointSize.w*this.coords[0];this.top=this.mapPointSize.h*this.coords[1];b=this.map._smallCorner();this.smallPxCoords={x:this.left-b.x,y:this.top-b.y}};
BattleMage.NPC.prototype._direction=function(){switch(Math.floor(4*Math.random()+1)){case 1:var b=RPG.N;break;case 2:b=RPG.S;break;case 3:b=RPG.E;break;case 4:b=RPG.W;break;default:b=RPG.N}return b};
BattleMage.NPC.prototype._moveCoords=function(){var b=RPG.NONE,c=this.dung.player.getCoords(),d=0;do{if(8==d)return{coords:this.coords,dir:this.direction};d++;var f=this._direction(),b=RPG.DIR[f],g=[this.coords[0]+b[0],this.coords[1]+b[1]],h=g[0],k=g[1];0>h?h=0:h>this.map.MAP[0].length-1&&(h=this.map.MAP[0].length-1);0>k?k=0:k>this.map.MAP.length-1&&(k=this.map.MAP.length-1);b=this.map.MAP[h][k];c[0]==h&&c[1]==k&&(b=RPG.YOU)}while(b==RPG.WALL||b==RPG.YOU);return{coords:g,dir:f}};
BattleMage.NPC.prototype._isOnRange=function(b){var c=this.dung.player.getCoords(),d=c[0]-b[0],b=c[1]-b[1],d=Math.sqrt(d*d+b*b);return d<this.dung.opt.radius?d:0};BattleMage.NPC.prototype._nearCoords=function(){var b=this._isOnRange(this.coords),c=[],d={},f=0;do{var g=this._moveCoords(),h=this._isOnRange(g.coords);if(2>h){this._attack();break}-1==c.indexOf(h)&&(c.push(h),d[h]=g);if(8==f)return d[c.min()];f++}while(h>=b);return g};
BattleMage.NPC.prototype._move=function(){this.oldCoords=[this.coords[0],this.coords[1]];var b=this._isOnRange(this.coords)?this._nearCoords():this._moveCoords();this.coords=b.coords;this.direction=b.dir;this.moving=!0;this.moveTime=(new Date).getTime()};BattleMage.NPC.prototype._attack=function(){this.makeEvent("npcAttack",{dmg:this.DMG})};"object"!=typeof window.JAK&&(window.JAK={NAME:"JAK"});JAK.idGenerator=function(){this.idCnt=this.idCnt<1E7?this.idCnt:0;var b="m"+(new Date).getTime().toString(16)+"m"+this.idCnt.toString(16);this.idCnt++;return b};Function.prototype.bind||(Function.prototype.bind=function(b){var c=this,d=Array.prototype.slice.call(arguments,1);return function(){return c.apply(b,d.concat(Array.prototype.slice.call(arguments)))}});
Array.prototype.indexOf||(Array.prototype.indexOf=function(b,c){var d=this.length,f=c||0;for(f<0&&(f=f+d);f<d;f++)if(f in this&&this[f]===b)return f;return-1});Array.indexOf||(Array.indexOf=function(b,c,d){return Array.prototype.indexOf.call(b,c,d)});Array.prototype.lastIndexOf||(Array.prototype.lastIndexOf=function(b,c){var d=this.length,f=c||d-1;for(f<0&&(f=f+d);f>-1;f--)if(f in this&&this[f]===b)return f;return-1});
Array.lastIndexOf||(Array.lastIndexOf=function(b,c,d){return Array.prototype.lastIndexOf.call(b,c,d)});Array.prototype.forEach||(Array.prototype.forEach=function(b,c){for(var d=this.length,f=0;f<d;f++)f in this&&b.call(c,this[f],f,this)});Array.forEach||(Array.forEach=function(b,c,d){Array.prototype.forEach.call(b,c,d)});Array.prototype.every||(Array.prototype.every=function(b,c){for(var d=this.length,f=0;f<d;f++)if(f in this&&!b.call(c,this[f],f,this))return false;return true});
Array.every||(Array.every=function(b,c,d){return Array.prototype.every.call(b,c,d)});Array.prototype.some||(Array.prototype.some=function(b,c){for(var d=this.length,f=0;f<d;f++)if(f in this&&b.call(c,this[f],f,this))return true;return false});Array.some||(Array.some=function(b,c,d){return Array.prototype.some.call(b,c,d)});Array.prototype.map||(Array.prototype.map=function(b,c){for(var d=this.length,f=Array(d),g=0;g<d;g++)g in this&&(f[g]=b.call(c,this[g],g,this));return f});
Array.map||(Array.map=function(b,c,d){return Array.prototype.map.call(b,c,d)});Array.prototype.filter||(Array.prototype.filter=function(b,c){for(var d=this.length,f=[],g=0;g<d;g++)if(g in this){var h=this[g];b.call(c,h,g,this)&&f.push(h)}return f});Array.filter||(Array.filter=function(b,c,d){return Array.prototype.filter.call(b,c,d)});String.prototype.lpad=function(b,c){for(var d=b||"0",f=c||2,g="";g.length<f-this.length;)g=g+d;g=g.substring(0,f-this.length);return g+this};
String.prototype.rpad=function(b,c){for(var d=b||"0",f=c||2,g="";g.length<f-this.length;)g=g+d;g=g.substring(0,f-this.length);return this+g};String.prototype.trim=function(){return this.match(/^\s*([\s\S]*?)\s*$/)[1]};String.trim||(String.trim=function(b){return String.prototype.trim.call(b)});Date.prototype._dayNames="Pond\u011bl\u00ed \u00dater\u00fd St\u0159eda \u010ctvrtek P\u00e1tek Sobota Ned\u011ble".split(" ");Date.prototype._dayNamesShort="Po \u00dat St \u010ct P\u00e1 So Ne".split(" ");
Date.prototype._monthNames="Leden \u00danor B\u0159ezen Duben Kv\u011bten \u010cerven \u010cervenec Srpen Z\u00e1\u0159\u00ed \u0158\u00edjen Listopad Prosinec".split(" ");Date.prototype._monthNamesShort="Led \u00dano B\u0159e Dub Kv\u011b \u010cer \u010crc Srp Z\u00e1\u0159 \u0158\u00edj Lis Pro".split(" ");
Date.prototype.format=function(b){for(var c={1:"st",2:"nd",3:"rd",21:"st",22:"nd",23:"rd",31:"st"},d="",f=false,g=0;g<b.length;g++){var h=b.charAt(g);if(f){f=false;d=d+h}else switch(h){case "\\":if(f){f=false;d=d+h}else f=true;break;case "d":d=d+this.getDate().toString().lpad();break;case "j":d=d+this.getDate();break;case "w":d=d+this.getDay();break;case "N":d=d+(this.getDay()||7);break;case "S":h=this.getDate();d=d+(c[h]||"th");break;case "D":d=d+this._dayNamesShort[(this.getDay()||7)-1];break;case "l":d=
d+this._dayNames[(this.getDay()||7)-1];break;case "z":var k=this.getTime(),h=new Date(k);h.setDate(1);h.setMonth(0);h=k-h.getTime();d=d+h/864E5;break;case "W":var h=new Date(this.getFullYear(),this.getMonth(),this.getDate()),l=h.getDay()||7;h.setDate(h.getDate()+(4-l));k=h.getFullYear();l=Math.floor((h.getTime()-new Date(k,0,1,-6))/864E5);d=d+(1+Math.floor(l/7)).toString().lpad();break;case "m":d=d+(this.getMonth()+1).toString().lpad();break;case "n":d=d+(this.getMonth()+1);break;case "M":d=d+this._monthNamesShort[this.getMonth()];
break;case "F":d=d+this._monthNames[this.getMonth()];break;case "t":var k=this.getTime(),o=this.getMonth(),h=new Date(k);do{l=h.getDate();k=k+864E5;h=new Date(k)}while(o==h.getMonth());d=d+l;break;case "L":h=new Date(this.getTime());h.setDate(1);h.setMonth(1);h.setDate(29);d=d+(h.getMonth()==1?"1":"0");break;case "Y":d=d+this.getFullYear().toString().lpad();break;case "y":d=d+this.getFullYear().toString().lpad().substring(2);break;case "a":d=d+(this.getHours()<12?"am":"pm");break;case "A":d=d+(this.getHours()<
12?"AM":"PM");break;case "G":d=d+this.getHours();break;case "H":d=d+this.getHours().toString().lpad();break;case "g":d=d+this.getHours()%12;break;case "h":d=d+(this.getHours()%12).toString().lpad();break;case "i":d=d+this.getMinutes().toString().lpad();break;case "s":d=d+this.getSeconds().toString().lpad();break;case "Z":d=d+-60*this.getTimezoneOffset();break;case "O":case "P":k=this.getTimezoneOffset()/-60;l=Math.abs(k).toString().lpad();h=="P"&&(l=l+":");l=l+"00";d=d+((k>=0?"+":"-")+l);break;case "U":d=
d+this.getTime()/1E3;break;case "u":d=d+"0";break;case "c":d=d+(arguments.callee.call(this,"Y-m-d")+"T"+arguments.callee.call(this,"H:i:sP"));break;case "r":d=d+arguments.callee.call(this,"D, j M Y H:i:s O");break;default:d=d+h}}return d};
window.JSON||function(){var b={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},c="[",d;for(d in b)c=c+("\\"+d);var c=c+"]",c=RegExp(c,"g"),f=function(d){return'"'+d.replace(c,function(c){return b[c]})+'"'},g=function(b,c,d,g){var p=Array(g+1).join(d);if(b===null)return"null";switch(typeof b){case "string":return f(b);case "boolean":case "number":return b.toString();case "object":var n="";if(b instanceof Array){for(var n=n+"[",q=0;q<b.length;q++){var t=b[q];if(q>
0){n=n+",";d.length&&(n=n+("\n"+p+d))}n=n+arguments.callee(t,c,d,g+1)}b.length>1&&d.length&&(n=n+("\n"+p));n=n+"]"}else{var n=n+"{",q=0,r;for(r in b){t=b[r];q>0&&(n=n+",");d.length&&(n=n+("\n"+p+d));n=n+(f(r)+":"+arguments.callee(t,c,d,g+1));q++}q>0&&d.length&&(n=n+("\n"+p));n=n+"}"}return n;default:return"undefined"}};window.JSON={parse:function(b){return eval("("+b+")")},stringify:function(b,c,d){var f="";typeof d=="number"&&d>1?f=Array(d+1).join(" "):typeof d=="string"&&(f=d);return g(b,c,f,0)}}}();
window.console||(window.console={log:function(){}});JAK.ClassMaker={};JAK.ClassMaker.VERSION="5.1";JAK.ClassMaker.NAME="JAK.ClassMaker";
JAK.ClassMaker.makeClass=function(b){var b=this._makeDefaultParams(b),c=function(){if(JAK.Browser.client=="gecko"&&JAK.Browser.version=="4"&&!c.__ff4_hack){for(var b in this)typeof this[b];c.__ff4_hack=true}b=false;if("$constructor"in arguments.callee.prototype)b=arguments.callee.prototype.$constructor;b&&b.apply(this,arguments)};return this._addConstructorProperties(c,b)};
JAK.ClassMaker.makeSingleton=function(b){var b=this._makeDefaultParams(b),c=function(){throw Error("Cannot instantiate singleton class");};c._instance=null;c.getInstance=this._getInstance;return this._addConstructorProperties(c,b)};JAK.ClassMaker.makeInterface=function(b){return this._addConstructorProperties(function(){throw Error("Cannot instantiate interface");},this._makeDefaultParams(b))};
JAK.ClassMaker.makeStatic=function(b){var b=this._makeDefaultParams(b),c={};c.VERSION=b.VERSION;c.NAME=b.NAME;return c};
JAK.ClassMaker._makeDefaultParams=function(b){if("EXTEND"in b){if(!b.EXTEND)throw Error("Cannot extend non-exist class");if(!("NAME"in b.EXTEND))throw Error("Cannot extend non-JAK class");}b.NAME=b.NAME||false;b.VERSION=b.VERSION||"1.0";b.EXTEND=b.EXTEND||false;b.IMPLEMENT=b.IMPLEMENT||[];b.DEPEND=b.DEPEND||[];if(!(b.IMPLEMENT instanceof Array))b.IMPLEMENT=[b.IMPLEMENT];this._preMakeTests(b);return b};
JAK.ClassMaker._preMakeTests=function(b){if(!b.NAME)throw Error("No NAME passed to JAK.ClassMaker.makeClass()");var c=false;if(c=this._testDepend(b.DEPEND))throw Error("Dependency error in class "+b.NAME+" ("+c+")");};JAK.ClassMaker._addConstructorProperties=function(b,c){for(var d in c)b[d]=c[d];this._setInheritance(b);b.prototype.constructor=b;b.prototype.$super=this._$super;return b};
JAK.ClassMaker._getInstance=function(){if(!this._instance){var b=function(){};b.prototype=this.prototype;this._instance=new b;"$constructor"in this.prototype&&this._instance.$constructor()}return this._instance};JAK.ClassMaker._setInheritance=function(b){b.EXTEND&&this._makeInheritance(b,b.EXTEND);for(var c=0;c<b.IMPLEMENT.length;c++)this._makeInheritance(b,b.IMPLEMENT[c],true)};
JAK.ClassMaker._makeInheritance=function(b,c,d){for(var f in c.prototype){var g=c.prototype[f];if(typeof g=="function"&&!g.owner)g.owner=c}if(d)for(f in c.prototype)b.prototype[f]=typeof c.prototype[f]=="object"?JSON.parse(JSON.stringify(c.prototype[f])):c.prototype[f];else{d=function(){};d.prototype=c.prototype;b.prototype=new d;for(f in c.prototype)typeof c.prototype[f]=="object"&&(b.prototype[f]=JSON.parse(JSON.stringify(c.prototype[f])))}};
JAK.ClassMaker._testDepend=function(b){for(var c=0;c<b.length;c++){var d=b[c];if(!d.sClass)return"Unsatisfied dependency";if(!d.ver)return"Version not specified in dependency";var f=d.sClass.VERSION.split(".")[0],g=d.ver.split(".")[0];if(f!=g)return"Version conflict in "+d.sClass.NAME}return false};
JAK.ClassMaker._$super=function(){var b=arguments.callee.caller;if(!b)throw Error("Function.prototype.caller not supported");var c=b.owner||this.constructor,d=false,f;for(f in c.prototype)if(c.prototype[f]==b){d=f;break}if(!d)throw Error("Cannot find supplied method in constructor");b=c.EXTEND;if(!b)throw Error("No super-class available");if(!b.prototype[d])throw Error("Super-class doesn't have method '"+d+"'");return b.prototype[d].apply(this,arguments)};
JAK.Events=JAK.ClassMaker.makeStatic({NAME:"JAK.Events",VERSION:"3.0"});JAK.Events._eventFolder={};JAK.Events._domReadyTimer=null;JAK.Events._domReadyCallback=[];JAK.Events._domReadyAlreadyRun=!1;JAK.Events._windowLoadListenerId=!1;JAK.Events.onDomReady=function(b,c){JAK.Events._domReadyCallback[JAK.Events._domReadyCallback.length]={obj:b,func:c};JAK.Events._onDomReady()};
JAK.Events._onDomReady=function(){if(/Safari/i.test(navigator.userAgent)||/WebKit|Khtml/i.test(navigator.userAgent))JAK.Events._domReadyTimer=setInterval(function(){if(/loaded|complete/.test(document.readyState)){clearInterval(JAK.Events._domReadyTimer);JAK.Events._domReady()}},10);else if(document.all&&!window.opera)if(window.parent==window){try{document.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,1);return}JAK.Events._domReady()}else JAK.Events._windowLoadListenerId=JAK.Events.addListener(window,
"load",window,function(){JAK.Events._domReady()});else document.addEventListener?document.addEventListener("DOMContentLoaded",JAK.Events._domReady,false):JAK.Events._windowLoadListenerId=JAK.Events.addListener(window,"load",window,function(){JAK.Events._domReady()})};
JAK.Events._domReady=function(){if(!JAK.Events._domReadyAlreadyRun){JAK.Events._domReadyAlreadyRun=true;document.addEventListener&&document.removeEventListener("DOMContentLoaded",JAK.Events._domReady,true);if(JAK.Events._windowLoadListenerId){JAK.Events.removeListener(JAK.Events._windowLoadListenerId);JAK.Events._windowLoadListenerId=false}for(var b=0;b<JAK.Events._domReadyCallback.length;b++){var c=JAK.Events._domReadyCallback[b];if(typeof c.func=="string")c.obj[c.func]();else c.func.apply(c.obj,
[])}JAK.Events._domReadyCallback=[]}};JAK.Events.addListener=function(b,c,d,f,g){var g=g||false,h=null,k=JAK.idGenerator();if(arguments.length>3){if(typeof f=="string"&&typeof d[f]!="function")throw Error("Events.addListener: arguments[3] must be method of arguments[2]");h=this._getMethod(d,f,b,k)}else h=this._getMethod(window,d,b,k);this._addListener(b,c,h,g);this._eventFolder[k]={elm:b,type:c,action:h,capture:g,obj:d,func:f};return k};
JAK.Events._addListener=function(b,c,d,f){if(document.addEventListener)b.addEventListener(c,d,f);else if(document.attachEvent)b.attachEvent("on"+c,d);else throw Error("This browser can not handle events");};JAK.Events._getMethod=function(b,c,d,f){var g=typeof c=="string"?b[c]:c;return function(c){return g.call(b,c,d,f)}};
JAK.Events.removeListener=function(b){if(!(b in this._eventFolder))throw Error("Cannot remove non-existent event ID '"+b+"'");var c=this._eventFolder[b];this._removeListener(c.elm,c.type,c.action,c.capture);delete this._eventFolder[b]};JAK.Events._removeListener=function(b,c,d,f){document.removeEventListener?b.removeEventListener(c,d,f):document.detachEvent&&b.detachEvent("on"+c,d)};JAK.Events.removeListeners=function(b){for(;b.length;)this.removeListener(b.shift())};
JAK.Events.removeAllListeners=function(){for(var b in this._eventFolder)this.removeListener(b)};JAK.Events.stopEvent=function(b){b=b||window.event;b.stopPropagation?b.stopPropagation():b.cancelBubble=true};JAK.Events.cancelDef=function(b){b=b||window.event;b.preventDefault?b.preventDefault():b.returnValue=false};JAK.Events.getTarget=function(b){b=b||window.event;return b.target||b.srcElement};
JAK.Events.getInfo=function(){var b=[],c=[],d=[],f;for(f in JAK.Events._eventFolder){var g=JAK.Events._eventFolder[f],h=g.elm,k=c.indexOf(h);if(k==-1){k=c.push(h)-1;d[k]=[]}d[k].push(g)}for(f=0;f<c.length;f++){h=[];for(k=0;k<d[f].length;k++){var g=d[f][k],l=g.obj||window,o=g.func||g.obj;h.push({sType:g.type,bRemoved:false,sFunction:(l!=window&&l.constructor?"["+l.constructor.NAME+"]":"")+(typeof o=="string"?"."+o+" = "+l[o].toString():" "+o.toString())})}b.push({sSource:"JAK",nNode:c[f],aListeners:h})}return b};
JAK.Browser=JAK.ClassMaker.makeStatic({NAME:"JAK.Browser",VERSION:"3.0"});JAK.Browser.platform="";JAK.Browser.client="";JAK.Browser.version=0;JAK.Browser.agent="";JAK.Browser.mouse={};JAK.Browser._getPlatform=function(){return this._agent.indexOf("X11")!=-1||this._agent.indexOf("Linux")!=-1?"nix":this._agent.indexOf("Mac")!=-1?"mac":this._agent.indexOf("Win")!=-1?"win":"oth"};
JAK.Browser._getClient=function(){return window.opera?"opera":window.chrome?"chrome":document.attachEvent&&typeof navigator.systemLanguage!="undefined"?"ie":document.getAnonymousElementByAttribute?"gecko":this._agent.indexOf("KHTML")!=-1?this._vendor=="KDE"?"konqueror":"safari":"oth"};
JAK.Browser._getMouse=function(){var b,c;if(JAK.Browser.client=="ie"&&parseFloat(JAK.Browser.version)<9){b=1;c=4}else if(JAK.Browser.client=="konqueror")if(parseFloat(JAK.Browser.version)<4){b=1;c=4}else{b=0;c=1}else if(JAK.Browser.client=="opera"&&JAK.Browser.version>7&&JAK.Browser.version<9){b=1;c=4}else if(JAK.Browser.client=="safari")if(parseInt(JAK.Browser.version)>2)c=b=0;else c=b=1;else{b=0;c=1}return{left:b,right:2,middle:c}};
JAK.Browser._getVersion=function(){var b="_get_"+this.client+"_ver";return typeof this[b]=="function"?this[b]():0};JAK.Browser._get_ie_ver=function(){return typeof Function.prototype.call!="undefined"?"draggable"in document.createElement("div")?"10":document.addEventListener?"9":window.XDomainRequest?"8":window.XMLHttpRequest?"7":typeof document.doctype=="object"?"6":"5.5":"5.0"};JAK.Browser._get_opera_ver=function(){return window.opera.version?window.opera.version():document.createComment?"7":"6"};
JAK.Browser._get_gecko_ver=function(){return"textOverflow"in document.createElement("div").style?"7":window.EventSource?"6":"onloadend"in new XMLHttpRequest?"5":history.pushState?"4":document.getBoxObjectFor===void 0?"3.6":navigator.geolocation?"3.5":document.getElementsByClassName?"3":window.external?"2":"1.5"};JAK.Browser._get_konqueror_ver=function(){var b=this._agent.substring(this._agent.indexOf("KHTML")+6),c=b.indexOf(" ");return b.substring(0,c-2)};
JAK.Browser._get_safari_ver=function(){var b=this._agent.match(/version\/([0-9]+)/i);return b?b[1]:"1"};JAK.Browser._get_chrome_ver=function(){var b=this._agent.match(/Chrome\/([0-9]+)/i);return b?b[1]:null};
JAK.Browser.isOld=function(){if(this.client=="ie"&&parseFloat(this.version)<=5.5||this.client=="opera"&&parseFloat(this.version)<9.5||this.client=="gecko"&&parseFloat(this.version)<2||this.client=="konqueror"&&parseFloat(this.version)<3.5||!document.documentElement||!document.documentElement.addEventListener&&!document.documentElement.attachEvent)return true;var b=function(){};return!b.call||!b.apply?true:false};
JAK.Browser.getBrowser=function(){this._agent=this.agent=navigator.userAgent;this._platform=navigator.platform;this._vendor=navigator.vendor;this.platform=this._getPlatform();this.client=this._getClient();this.version=this._getVersion();this.mouse=this._getMouse()};JAK.Browser.getBrowser();JAK.DOM=JAK.ClassMaker.makeStatic({NAME:"JAK.DOM",VERSION:"5.0"});JAK.cel=function(b,c,d,f){b=(f||document).createElement(b);if(c)b.className=c;if(d)b.id=d;return b};
JAK.mel=function(b,c,d,f){b=(f||document).createElement(b);if(c)for(var g in c)b[g]=c[g];d&&JAK.DOM.setStyle(b,d);return b};JAK.ctext=function(b,c){return(c||document).createTextNode(b)};JAK.gel=function(b,c){var d=c||document;return typeof b=="string"?d.getElementById(b):b};
JAK.query=function(b){for(var c=function(b,c){for(var d=[],f=0;f<b.length;f++){for(var g=b[f],h=true,k=0;k<c.length;k++){var l=c[k],j=l.charAt(0),l=l.substr(1).toLowerCase();j=="#"&&l!=g.id.toLowerCase()&&(h=false);j=="."&&!JAK.DOM.hasClass(g,l)&&(h=false)}h&&d.push(g)}return d},d=[],b=b.split(",");b.length;){for(var f=b.shift().trim().split(/ +/),g=[document],h=0;h<f.length;h++){for(var k=[],l=f[h],o=l.match(/^[a-z]*/i)[0]||"*",l=l.match(/[\.#][^\.#]+/g)||[];g.length;)var p=g.shift().getElementsByTagName(o),
k=k.concat(c(p,l));g=k}for(h=0;h<g.length;h++){f=g[h];d.indexOf(f)==-1&&d.push(f)}}return d};JAK.DOM.append=function(){for(var b=0;b<arguments.length;b++)for(var c=arguments[b],d=c[0],f=1;f<c.length;f++)d.appendChild(c[f])};JAK.DOM.hasClass=function(b,c){for(var d=b.className.split(" "),f=0;f<d.length;f++)if(d[f].toLowerCase()==c.toLowerCase())return true;return false};JAK.DOM.addClass=function(b,c){if(!JAK.DOM.hasClass(b,c))b.className=b.className+(" "+c)};
JAK.DOM.removeClass=function(b,c){for(var d=b.className.split(" "),f=[],g=0;g<d.length;g++)d[g].toLowerCase()!=c.toLowerCase()&&f.push(d[g]);b.className=f.join(" ")};JAK.DOM.clear=function(b){for(;b.firstChild;)b.removeChild(b.firstChild)};
JAK.DOM.getDocSize=function(){var b=0,c=0;if(document.compatMode!="BackCompat"){if(document.documentElement.clientWidth&&JAK.Browser.client!="opera"){b=document.documentElement.clientWidth;c=document.documentElement.clientHeight}else if(JAK.Browser.client=="opera")if(parseFloat(JAK.Browser.version)<9.5){b=document.body.clientWidth;c=document.body.clientHeight}else{b=document.documentElement.clientWidth;c=document.documentElement.clientHeight}if(JAK.Browser.client=="safari"||JAK.Browser.client=="konqueror")c=
window.innerHeight}else{b=document.body.clientWidth;c=document.body.clientHeight}return{width:b,height:c}};
JAK.DOM.getBoxPosition=function(b,c){var d=0,f=0,g=c||b.ownerDocument.body;if(b.getBoundingClientRect&&!c){d=document.documentElement;f=b.getBoundingClientRect();g=JAK.DOM.getBoxScroll(b);return{left:f.left+g.x-d.clientLeft,top:f.top+g.y-d.clientTop}}for(;b&&b!=g;){d=d+b.offsetTop;f=f+b.offsetLeft;if((JAK.Browser.client=="gecko"&&JAK.Browser.version<3||JAK.Browser.client=="safari")&&JAK.DOM.getStyle(b,"position")=="fixed"){g=JAK.DOM.getScrollPos();d=d+g.y;f=f+g.x;break}b=b.offsetParent}return{top:d,
left:f}};JAK.DOM.getPortBoxPosition=function(b,c,d){var f=JAK.DOM.getBoxPosition(b,c,d),b=JAK.DOM.getBoxScroll(b,c,d);f.left=f.left-b.x;f.top=f.top-b.y;return{left:f.left,top:f.top}};
JAK.DOM.getBoxScroll=function(b,c,d){for(var f=0,g=0,h=b.parentNode,b=c||b.ownerDocument.documentElement,c=false;;)if(JAK.Browser.client=="opera"&&JAK.DOM.getStyle(h,"display")!="block")h=h.parentNode;else if(JAK.Browser.client=="opera"&&JAK.Browser.version<9.5&&h==document.body)h=h.parentNode;else{d&&JAK.DOM.getStyle(h,"position")=="fixed"&&(c=true);if(!c){f=f+h.scrollLeft;g=g+h.scrollTop}if(h==b)break;h=h.parentNode;if(!h)break}return{x:f,y:g}};
JAK.DOM.getScrollPos=function(){if(document.documentElement.scrollTop||document.documentElement.scrollLeft)var b=document.documentElement.scrollLeft,c=document.documentElement.scrollTop;else if(document.body.scrollTop||document.body.scrollLeft){b=document.body.scrollLeft;c=document.body.scrollTop}else c=b=0;return{x:b,y:c}};JAK.DOM.getStyle=function(b,c){if(document.defaultView&&document.defaultView.getComputedStyle){var d=b.ownerDocument.defaultView.getComputedStyle(b,"");return!d?false:d[c]}return b.currentStyle[c]};
JAK.DOM.setStyle=function(b,c){for(var d in c)b.style[d]=c[d]};JAK.DOM.writeStyle=function(b){var c=JAK.mel("style",{type:"text/css"});c.styleSheet?c.styleSheet.cssText=b:c.appendChild(JAK.ctext(b));b=document.getElementsByTagName("head");if(b.length)b=b[0];else{b=JAK.cel("head");document.documentElement.appendChild(b,document.body)}b.appendChild(c);return c};
JAK.DOM.elementsHider=function(b,c,d){function f(c){for(var d=false;c.parentNode&&c!=document;){c==b&&(d=true);c=c.parentNode}return d}var g=c;g||(g=["select","object","embed","iframe"]);var h=arguments.callee.hidden;if(h){h.forEach(function(b){b.style.visibility="visible"});arguments.callee.hidden=[]}if(d=="hide"){typeof b=="string"&&(b=JAK.gel(b));var h=[],k=this.getBoxPosition(b);k.width=b.offsetWidth+k.left;k.height=b.offsetHeight+k.top;for(var l=0;l<g.length;++l)for(var o=document.getElementsByTagName(g[l]),
p=0;p<o.length;++p){var n=this.getBoxPosition(o[p]);if(!f(o[p])){n.width=o[p].offsetWidth+n.left;n.height=o[p].offsetHeight+n.top;if(!(k.left>n.width||k.width<n.left||k.top>n.height||k.height<n.top)){o[p].style.visibility="hidden";h.push(o[p])}}}arguments.callee.hidden=h}};
JAK.DOM.getElementsByClass=function(b,c,d){if(document.getElementsByClassName&&!d){var f=c||document;return JAK.DOM.arrayFromCollection(f.getElementsByClassName(b))}if(document.querySelectorAll&&!d){f=c||document;return JAK.DOM.arrayFromCollection(f.querySelectorAll("."+b))}for(var f=[],c=c||document,c=c.getElementsByTagName(d||"*"),d=c.length,b=RegExp("(^|\\s)"+b+"(\\s|$)"),g=0,h=0;g<d;g++)if(b.test(c[g].className)){f[h]=c[g];h++}return f};
JAK.DOM.arrayFromCollection=function(b){var c=[];try{c=Array.prototype.slice.call(b)}catch(d){for(var f=0;f<b.length;f++)c.push(b[f])}finally{return c}};JAK.DOM.separateCode=function(b){var c=[];return[b.replace(/<script.*?>([\s\S]*?)<\/script>/g,function(b,f){c.push(f);return""}),c.join("\n")]};
JAK.DOM.shiftBox=function(b){var c=0,d=0,f=JAK.DOM.getBoxPosition(b),g=JAK.DOM.getScrollPos();f.left=f.left-g.x;f.top=f.top-g.y;var g=JAK.DOM.getDocSize(),h=b.offsetWidth,b=f.top+b.offsetHeight-g.height;if(b>0){f.top=f.top-b;d=d-b}b=f.left+h-g.width;if(b>0){f.left=f.left-b;c=c-b}b=f.top;if(b<0){f.top=f.top-b;d=d-b}b=f.left;if(b<0){f.left=f.left-b;c=c-b}return[c,d]};
JAK.DOM.scrollbarWidth=function(){var b=JAK.mel("div",false,{width:"50px",height:"50px",overflow:"hidden",position:"absolute",left:"-200px"}),c=JAK.mel("div",false,{height:"100px"});b.appendChild(c);document.body.insertBefore(b,document.body.firstChild);c=b.clientWidth+parseInt(JAK.DOM.getStyle(b,"paddingLeft"))+parseInt(JAK.DOM.getStyle(b,"paddingRight"));JAK.DOM.setStyle(b,{overflowY:"scroll"});var d=b.clientWidth+parseInt(JAK.DOM.getStyle(b,"paddingLeft"))+parseInt(JAK.DOM.getStyle(b,"paddingRight"));
document.body.removeChild(b);return c-d};JAK.ObjLib=JAK.ClassMaker.makeClass({NAME:"ObjLib",VERSION:"3.1"});JAK.ObjLib.prototype.reSetOptions=function(){};JAK.ObjLib.prototype.pretty=function(b){return b};JAK.ObjLib.prototype.serialize=function(b){return JSON.stringify(b)};JAK.ObjLib.prototype.unserialize=function(b){return JSON.parse(b)};JAK.ObjLib.prototype.match=function(b,c){return JSON.stringify(b)==JSON.stringify(c)};JAK.ObjLib.prototype.copy=function(b){return JSON.parse(JSON.stringify(b))};
JAK.ObjLib.prototype.arrayCopy=function(b){return this.copy(b)};JAK.Request=JAK.ClassMaker.makeClass({NAME:"JAK.Request",VERSION:"2.0"});JAK.Request.XML=0;JAK.Request.TEXT=1;JAK.Request.JSONP=2;JAK.Request.BINARY=3;JAK.Request.supportsCrossOrigin=function(){return JAK.Browser.client=="opera"||JAK.Browser.client=="ie"&&JAK.Browser.version<8?false:true};
JAK.Request.prototype.$constructor=function(b,c){this._NEW=0;this._SENT=1;this._DONE=2;this._ABORTED=3;this._TIMEOUT=4;this._xhr=null;this._callback="";this._script=null;this._type=b;this._headers={};this._callbacks={};this._state=this._NEW;this._xdomain=false;this._options={async:true,timeout:0,method:"get"};for(var d in c)this._options[d]=c[d];if(this._type==JAK.Request.JSONP){if(this._options.method.toLowerCase()=="post")throw Error("POST not supported in JSONP mode");if(!this._options.async)throw Error("Async not supported in JSONP mode");
}};JAK.Request.prototype.$destructor=function(){this._state==this._SENT&&this.abort();this._xhr=null};JAK.Request.prototype.setHeaders=function(b){if(this._type==JAK.Request.JSONP)throw Error("Request headers not supported in JSONP mode");for(var c in b)this._headers[c]=b[c]};
JAK.Request.prototype.getHeaders=function(){if(this._state!=this._DONE)throw Error("Response headers not available");if(this._type==JAK.Request.JSONP)throw Error("Response headers not supported in JSONP mode");var b={},c=this._xhr.getAllResponseHeaders();if(c)for(var c=c.split(/[\r\n]/),d=0;d<c.length;d++)if(c[d]){var f=c[d].match(/^([^:]+): *(.*)$/);b[f[1]]=f[2]}return b};
JAK.Request.prototype.send=function(b,c){if(this._state!=this._NEW)throw Error("Request already sent");this._state=this._SENT;this._userCallback(this);switch(this._type){case JAK.Request.XML:case JAK.Request.TEXT:case JAK.Request.BINARY:return this._sendXHR(b,c);case JAK.Request.JSONP:return this._sendScript(b,c);default:throw Error("Unknown request type");}};
JAK.Request.prototype.abort=function(){if(this._state!=this._SENT)return false;this._state=this._ABORTED;this._xhr&&this._xhr.abort();this._userCallback(this);return true};JAK.Request.prototype.setCallback=function(b,c){this._setCallback(b,c,this._DONE);return this};JAK.Request.prototype.setSendCallback=function(b,c){this._setCallback(b,c,this._SENT);return this};JAK.Request.prototype.setAbortCallback=function(b,c){this._setCallback(b,c,this._ABORTED);return this};
JAK.Request.prototype.setTimeoutCallback=function(b,c){this._setCallback(b,c,this._TIMEOUT);return this};JAK.Request.prototype._setCallback=function(b,c,d){this._callbacks[d]=[b,c]};
JAK.Request.prototype._sendXHR=function(b,c){if(window.XMLHttpRequest){var d=XMLHttpRequest,f=b.match(/^https?\:\/\/(.*?)\//);if(f&&f[1]!=location.host&&window.XDomainRequest){if(this._type==JAK.Request.BINARY)throw Error("XDomainRequest does not support BINARY mode");this._xdomain=true;d=XDomainRequest}this._xhr=new d}else if(window.ActiveXObject)this._xhr=new ActiveXObject("Microsoft.XMLHTTP");else throw Error("No XHR available");this._xdomain?this._xhr.onload=this._onXDomainRequestLoad.bind(this):
this._xhr.onreadystatechange=this._onReadyStateChange.bind(this);if(this._options.method.toLowerCase()=="get"){d=this._buildURL(b,c);f=null}else{var d=b,f=this._serializeData(c),g=false,h;for(h in this._headers)if(h.toLowerCase()=="content-type"){g=true;break}g||this.setHeaders({"Content-Type":"application/x-www-form-urlencoded"})}if(this._type==JAK.Request.BINARY)if(this._xhr.overrideMimeType)this._xhr.overrideMimeType("text/plain; charset=x-user-defined");else if(JAK.Browser.client=="ie")this._buildVBS();
else throw Error("This browser does not support binary transfer");this._xhr.open(this._options.method,d,this._options.async);for(h in this._headers)this._xhr.setRequestHeader(h,this._headers[h]);this._xhr.send(f);this._options.timeout&&setTimeout(this._timeout.bind(this),this._options.timeout);this._options.async||this._onReadyStateChange();return d};
JAK.Request.prototype._sendScript=function(b,c){var d=c||{};this._callback="callback"+JAK.idGenerator();d.callback=this._callback;b=this._buildURL(b,d);window[this._callback]=this._scriptCallback.bind(this);this._script=JAK.mel("script",{type:"text/javascript",src:b});document.body.insertBefore(this._script,document.body.firstChild);return b};JAK.Request.prototype._buildURL=function(b,c){var d=this._serializeData(c);return!d.length?b:b.indexOf("?")==-1?b+"?"+d:b+"&"+d};
JAK.Request.prototype._serializeData=function(b){if(typeof b=="string"||window.File&&b instanceof File)return b;if(!b)return"";var c=[],d;for(d in b){var f=b[d];f instanceof Array||(f=[f]);for(var g=0;g<f.length;g++)c.push(encodeURIComponent(d)+"="+encodeURIComponent(f[g]))}return c.join("&")};
JAK.Request.prototype._onReadyStateChange=function(){if(this._state!=this._ABORTED&&this._xhr.readyState==4){var b=this._xhr.status,c;if(this._type==JAK.Request.BINARY){c=[];if(JAK.Browser.client=="ie")for(var d=VBS_getLength(this._xhr.responseBody),f=0;f<d;f++)c.push(VBS_getByte(this._xhr.responseBody,f));else for(var g=this._xhr.responseText,d=g.length,f=0;f<d;f++)c.push(g.charCodeAt(f)&255)}else c=this._type==JAK.Request.XML?this._xhr.responseXML:this._xhr.responseText;this._done(c,b)}};
JAK.Request.prototype._onXDomainRequestLoad=function(){if(this._state!=this._ABORTED){var b=this._xhr.responseText;if(this._type==JAK.Request.XML){var c=new ActiveXObject("Microsoft.XMLDOM");c.async=false;c.loadXML(b);b=c}this._done(b,200)}};JAK.Request.prototype._scriptCallback=function(b){this._script.parentNode.removeChild(this._script);this._script=null;delete window[this._callback];this._state!=this._ABORTED&&this._done(b,200)};
JAK.Request.prototype._done=function(b,c){this._state=this._DONE;this._userCallback(b,c,this)};JAK.Request.prototype._timeout=function(){if(this._state==this._SENT){this.abort();this._state=this._TIMEOUT;this._userCallback(this)}};JAK.Request.prototype._userCallback=function(){var b=this._callbacks[this._state];if(b){var c=b[0]||window,b=b[1];c&&typeof b=="string"&&(b=c[b]);if(!b){b=c;c=window}b.apply(c,arguments)}};
JAK.Request.prototype._buildVBS=function(){var b=JAK.mel("script",{type:"text/vbscript"});b.text="Function VBS_getByte(data, pos)\nVBS_getByte = AscB(MidB(data, pos+1,1))\nEnd Function\nFunction VBS_getLength(data)\nVBS_getLength = LenB(data)\nEnd Function";document.getElementsByTagName("head")[0].appendChild(b)};JAK.Signals=JAK.ClassMaker.makeClass({NAME:"JAK.Signals",VERSION:"2.1"});JAK.Signals.prototype.$constructor=function(){this._myHandleFolder={};this._myIdFolder={}};
JAK.Signals.prototype.addListener=function(b,c,d,f){c in this._myHandleFolder||(this._myHandleFolder[c]={});var c=this._myHandleFolder[c],g;for(g in c){var h=c[g];if(h.eFunction==d&&h.eOwner==b&&h.eSender==f)return null}g=JAK.idGenerator();c[g]={eOwner:b,eFunction:d,eSender:f};this._myIdFolder[g]=c;return g};JAK.Signals.prototype.removeListener=function(b){var c=this._myIdFolder[b];if(!c)throw Error("Cannot remove non-existent signal ID '"+b+"'");delete c[b];delete this._myIdFolder[b]};
JAK.Signals.prototype.removeListeners=function(b){for(;b.length;)this.removeListener(b.shift())};JAK.Signals.prototype.makeEvent=function(b,c,d){this._myEventHandler({type:b,target:c,timeStamp:(new Date).getTime(),data:d&&typeof d=="object"?d:null})};
JAK.Signals.prototype._myEventHandler=function(b){0;var c=[],d;for(d in this._myHandleFolder)if(d==b.type||d=="*")for(var f in this._myHandleFolder[d]){var g=this._myHandleFolder[d][f];(!g.eSender||g.eSender==b.target)&&c.push(g)}for(d=0;d<c.length;d++){g=c[d];f=g.eOwner;g=g.eFunction;if(typeof g=="string")f[g](b);else typeof g=="function"&&g(b)}};JAK.signals=new JAK.Signals;JAK.ISignals=JAK.ClassMaker.makeInterface({NAME:"JAK.ISignals",VERSION:"2.1"});
JAK.ISignals.prototype.setInterface=function(b){if(typeof this[b]!="object"){for(var c=this._owner;typeof c[b]=="undefined";){if(typeof c.TOP_LEVEL!="undefined")throw Error("SetInterface:Interface not found");c=c._owner}return c[b]}};JAK.ISignals.prototype.addListener=function(b,c,d){return this.getInterface().addListener(this,b,c,d)};JAK.ISignals.prototype.removeListener=function(b){return this.getInterface().removeListener(b)};JAK.ISignals.prototype.removeListeners=function(b){this.getInterface().removeListeners(b)};
JAK.ISignals.prototype.makeEvent=function(b,c){this.getInterface().makeEvent(b,this,c)};JAK.ISignals.prototype.getInterface=function(){return typeof this.signals=="object"?this.signals:JAK.signals};JAK.AbstractDecorator=JAK.ClassMaker.makeSingleton({NAME:"JAK.AbstractDecorator",VERSION:"2.0"});JAK.AbstractDecorator.prototype.decorate=function(b){b.$super=this._$super;if(!b.__decorators)b.__decorators=[];b.__decorators.push(this);return b};
JAK.AbstractDecorator.prototype._$super=function(){var b=arguments.callee.caller;if(!b)throw Error("Function.prototype.caller not supported");for(var c=this.__decorators||[],d=null,f=null,g=c.length;g--;){var h=c[g];if(!d&&f&&f in h){d=h;break}for(var k in h)if(!f&&b==h[k]){f=k;break}}if(f){if(!d){d=this.constructor.prototype;if(!(f in d))throw Error("Function '"+f+"' has no undecorated parent");}}else{d=b.owner||this.constructor;c=false;for(f in d.prototype)d.prototype[f]==b&&(c=f);if(!c)throw Error("Cannot find supplied method in constructor");
b=d.EXTEND;if(!b)throw Error("No super-class available");if(!b.prototype[c])throw Error("Super-class doesn't have method '"+c+"'");return b.prototype[c].apply(this,arguments)}return d[f].apply(this,arguments)};JAK.AutoDecorator=JAK.ClassMaker.makeSingleton({NAME:"JAK.AutoDecorator",VERSION:"1.0",EXTEND:JAK.AbstractDecorator});JAK.AutoDecorator.prototype.decorate=function(b){this.$super(b);var c=["constructor","$super","_$super","decorate"],d;for(d in this)c.indexOf(d)==-1&&(b[d]=this[d])};
JAK.IDecorable=JAK.ClassMaker.makeClass({NAME:"JAK.IDecorable",VERSION:"2.0",CLASS:"class"});JAK.IDecorable.prototype.decorate=function(b){for(var c=[this],d=1;d<arguments.length;d++)c.push(arguments[d]);d=b.getInstance();return d.decorate.apply(d,c)};var BattleMage={};RPG={N:0,NE:1,E:2,SE:3,S:4,SW:5,W:6,NW:7,CENTER:8,DIR:{}};RPG.DIR[RPG.N]=[0,-1];RPG.DIR[RPG.NE]=[1,-1];RPG.DIR[RPG.E]=[1,0];RPG.DIR[RPG.SE]=[1,1];RPG.DIR[RPG.S]=[0,1];RPG.DIR[RPG.SW]=[-1,1];RPG.DIR[RPG.W]=[-1,0];RPG.DIR[RPG.NW]=[-1,-1];RPG.DIR[RPG.CENTER]=[0,0];RPG.NONE=0;RPG.NPC=2;RPG.WALL=1;RPG.YOU=3;RPG.END=4;RPG.BLOOD=5;RPG.HP=500;RPG.speed=5;RPG.STYLE={};RPG.STYLE[RPG.NONE]={img:"./img/none.png",color:"rgb(255,255,255)",width:30,height:30};
RPG.STYLE[RPG.WALL]={img:"./img/wall.png",color:"#000",width:30,height:30};RPG.STYLE[RPG.NPC]={img:"./img/bluecape.png",color:"#FFF",up:0,left:0,right:0,down:0,width:30,height:30,steps:1,interval:0};RPG.STYLE[RPG.YOU]={img:"./img/man.png",color:"#FFF",up:0,left:0,right:0,down:0,width:30,height:30,steps:1,interval:0};Array.prototype.min=function(){return Math.min.apply(Math,this)};Array.prototype.max=function(){return Math.max.apply(Math,this)};
BattleMage.Dungeon=JAK.ClassMaker.makeClass({NAME:"BattleMage.Dungeon",VERSION:"0.5",IMPLEMENT:JAK.ISignals});
BattleMage.Dungeon.prototype.$constructor=function(b,c){this.Stats=new Stats;this.Stats.getDomElement().style.position="absolute";this.Stats.getDomElement().style.left="0px";this.Stats.getDomElement().style.top="0px";document.body.appendChild(this.Stats.getDomElement());this.opt={allMap:0,radius:7,visibility:!0,step:100,pointSize:{w:30,h:30}};this.direction=RPG.E;this.HP=RPG.HP;this.dom={};this.ec=[];var d=[[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1],[1,0,0,0,0,1,0,0,0,0,0,0,1,1,1,1,1,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1],[1,0,0,0,0,1,1,1,0,0,0,0,1,1,1,1,1,1,0,1,0,0,0,0,0,0,1,0,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1],[1,0,0,0,0,1,0,1,0,0,0,0,
0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1],[1,1,1,0,1,1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,0,1,1,1,1,1,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,0,1,1,0,1,1,0,0,0,1,1,1],[1,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0,1,0,0,0,1,0,1,0,1,0,1],[1,0,0,0,0,1,0,1,1,0,1,1,1,0,1,1,0,1,0,1,1,1,1,1,0,0,0,0,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,
1,0,1,0,1,0,1,0,0,1,0,0,0,1,1,1,1,1,0,1],[1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,1],[1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,1,0,1,1,0,1],[1,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,0,0,0,1,1,0,1,1,0,1],[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
1,1,1,1,1,0,1,0,0,1,0,1,1,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,0,0,1,0,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,1,0,1,0,0,0,1,1,0,1,1,0,1],[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,1,1,1,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,0,1,1,0,1],[1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,
0,0,0,0,0,0,1,0,0,0,0,0,0,0,1],[1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,1,1,1,1,1,0,1,0,1,1,0,1,1,0,1],[1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,0,0,0,1,0,1,0,1,1,0,1,1,0,1],[1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1],[1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,1,0,1,1,1,
1,1,0,0,0,1,0,0,0,0,1,0,1,0,1,0,1,0,0,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,0,0,0,1,0,1,0,1,1,0,1,1,0,1],[1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,1,1,1,1,1,0,1,0,1,1,0,1,1,0,1],[1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,1,0,1,0,0,1,1,1,1,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1],[1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,1,0,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,1,1,0,1,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,0,1,1,
1,1,1,1,1,0,1,1,1,1],[1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,1],[1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,1,0,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,1,1,1,1,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1],[1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,1,0,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1],[1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,1,0,1,0,
1,0,0,0,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1],[1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1],[1,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1],[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,
0,1,0,0,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]];this.optmap=c||d;this.shots=[];this.move=!1;this.timekeeper=JAK.Timekeeper.getInstance();this.cUtil=new BattleMage.cUtil(this.canvasMap);this.dom.root=JAK.gel(b);this.center={x:40,y:40};this._makeMap();this.addListener("map-loaded",this._mapLoaded.bind(this),this.map)};BattleMage.Dungeon.prototype.$destructor=function(){JAK.Events.removeListeners(this.ec)};
BattleMage.Dungeon.prototype._makeMap=function(){this.map=new RPGMAP.ImageMap({pointSize:this.opt.pointSize,mapElm:this.dom.root,allMap:this.opt.allMap,visibility:this.opt.visibility,radius:this.opt.radius,canvas:!0},this.optmap);this.map.setMidPoint(this.center);this.map.build()};BattleMage.Dungeon.prototype._mapLoaded=function(){this._makeEffectCanvas();this._makePlayer();this._makeNPCs();this._setTicker()};
BattleMage.Dungeon.prototype._makeNPCs=function(){this.npcs=[];this.npcs.push(new BattleMage.NPC(this,{startPos:{x:2,y:2},canvas:this.dom.canvasPlace}),new BattleMage.NPC(this,{startPos:{x:3,y:2},canvas:this.dom.canvasPlace}),new BattleMage.NPC(this,{canvas:this.dom.canvasPlace}),new BattleMage.NPC(this,{canvas:this.dom.canvasPlace}),new BattleMage.NPC(this,{canvas:this.dom.canvasPlace}),new BattleMage.NPC(this,{canvas:this.dom.canvasPlace}),new BattleMage.NPC(this,{canvas:this.dom.canvasPlace}),
new BattleMage.NPC(this,{canvas:this.dom.canvasPlace}),new BattleMage.NPC(this,{canvas:this.dom.canvasPlace}))};
BattleMage.Dungeon.prototype._makeEffectCanvas=function(){this.dom.canvasMap=this.map.getDomCanvas();this.canvasPos=JAK.DOM.getBoxPosition(this.map.getDomCanvas());this.canvasSize={width:this.map.getDomCanvas().width,height:this.map.getDomCanvas().height};this.dom.canvasPlace=JAK.mel("canvas",{width:this.canvasSize.width,height:this.canvasSize.height},{position:"absolute",top:this.canvasPos.top+"px",left:this.canvasPos.left+"px"});this.canvasPlace=this.dom.canvasPlace.getContext("2d");this.dom.canvasMap.parentNode.appendChild(this.dom.canvasPlace)};
BattleMage.Dungeon.prototype._clearCanvasPlace=function(){this.canvasPlace.clearRect(0,0,this.canvasSize.width,this.canvasSize.height)};BattleMage.Dungeon.prototype._makePlayer=function(){this.player=new BattleMage.Player(this,this.dom.canvasPlace);this.player.setCenter(this.center)};BattleMage.Dungeon.prototype.getMapInstance=function(){return this.map};BattleMage.Dungeon.prototype._setTicker=function(){this.timekeeper.addListener(this,"_tick",2)};
BattleMage.Dungeon.prototype._npcsUpdate=function(){for(var b=[],c=0;c<this.npcs.length;c++){var d=this.npcs[c];d.death?b.push(c):d.update()}for(c=0;c<b.length;c++)this.npcs.splice(b[c],1)};BattleMage.Dungeon.prototype._npcsDraw=function(){for(var b=0;b<this.npcs.length;b++)this.npcs[b].draw()};BattleMage.Dungeon.prototype._update=function(){this.map.setMidPoint(this.center);this.map.update();this.player.update();this._npcsUpdate()};
BattleMage.Dungeon.prototype._draw=function(){this.map.setMidPoint(this.center);this.map.update();this._clearCanvasPlace();this.player.draw();this._npcsDraw()};BattleMage.Dungeon.prototype._tick=function(){this._update();this._draw();this.Stats.update()};BattleMage.Attack=JAK.ClassMaker.makeClass({NAME:"BattleMage.Attack",VERSION:"1.0"});BattleMage.Attack.prototype.$constructor=function(b){this.player=b;this.dung=this.player.dung;this.SPRITE=this.player.SPRITE;this.DMG=10;this.direction=this.dung.direction;this.dom={};this.ec=[];this.dom.canvas=this.player.dom.canvas;this.canvas=this.dom.canvas.getContext("2d");this._makeAttackImg()};
BattleMage.Attack.prototype._makeAttackImg=function(){this.img=new Image;this.img.src="./img/Sword.png";this.imgSize={w:17,h:32};this.diffImageRotate=-90*Math.PI/180};BattleMage.Attack.prototype._getAttackAngle=function(){var b={start:0,end:0},c=e=0;switch(this.direction){case RPG.N:c=0;e=180;break;case RPG.E:c=90;e=270;break;case RPG.S:c=180;e=360;break;case RPG.W:c=270;e=450;break;default:return}b.start=Math.PI*c/180;b.end=Math.PI*e/180;return b};
BattleMage.Attack.prototype.draw=function(){var b=1.5*this.imgSize.w;sh=1.5*this.imgSize.h;this.canvas.save();this.canvas.translate(this.left+this.SPRITE.step*this.SPRITE.scale/2,this.top+this.SPRITE[this.direction].height*this.SPRITE.scale/2);this.canvas.rotate(this.diffImageRotate+this.attackObj.current);this.canvas.translate(-1*(b/2),-1*sh);this.canvas.drawImage(this.img,0,0,b,sh);this.canvas.restore()};
BattleMage.Attack.prototype._dmgNpcs=function(){for(var b=this.dung.npcs,c=[],d=0;d<b.length;d++)0<b[d]._isOnRange(b[d].getCoords())&&c.push(b[d]);for(d=0;d<c.length;d++){var f=b[d].getSmallPxCoords(),g=1.5*this.dung.opt.pointSize.w,h=f.x-this.left,k=f.y-this.top,f=Math.sqrt(h*h+k*k),h=this._isRightAngle(180*Math.atan2(k,h)/Math.PI);f<=g&&h&&b[d].getDmg(this.DMG)}};
BattleMage.Attack.prototype._isRightAngle=function(b){var c=!1;switch(this.direction){case RPG.N:s=-180;e=0;break;case RPG.E:s=-90;e=90;break;case RPG.S:s=0;e=180;break;case RPG.W:s=90;e=-90;if(90<b&&180>b||-90>b&&-180<b)c=!0;break;default:return}b>s&&b<e&&(c=!0);return c};
BattleMage.Attack.prototype.update=function(){var b=this.player.getPosition();this.left=b.x;this.top=b.y;this.direction=this.player.getDirection();0<=this._attackDir&&this._attackDir==this.direction?this.attackObj.current>=this.attackObj.end?(this._dmgNpcs(this.attackObj),this.attackObj.current=this.attackObj.start):this.attackObj.current=this.attackObj.step+this.attackObj.current:(this._attackDir=this.direction,b=this._getAttackAngle(),this.attackObj={start:b.start,end:b.end,step:(b.end-b.start)/
10,current:b.start})};BattleMage.cUtil=JAK.ClassMaker.makeClass({NAME:"BattleMage.cUtil",VERSION:"1.0"});BattleMage.cUtil.prototype.$constructor=function(b,c){this.canvas=b;this.color="#666";this.Lopt={lwidth:1,part:5,color:"#0000cc",lastDist:10};for(i in c)this.Lopt[i]=c[i]};BattleMage.cUtil.prototype.randRange=function(b,c){return-1*(Math.floor(Math.random()*(b-c+1))+b)};
BattleMage.cUtil.prototype.makeLine=function(b,c){this.canvas.save();this.canvas.beginPath();this.canvas.moveTo(b.x,b.y);this.canvas.lineTo(c.x,c.y);this.canvas.stroke();this.canvas.closePath();this.canvas.restore()};
BattleMage.cUtil.prototype.makeLight=function(b,c){this.canvas.save();this.canvas.beginPath();this.canvas.strokeStyle=this.Lopt.color;this.canvas.lineWidth=2;this.canvas.moveTo(b.x,b.y);for(var d=Math.atan2(c.y-b.y,c.x-b.x),f=Math.sqrt((b.x-c.x)*(b.x-c.x)+(b.y-c.y)*(b.y-c.y)),g=0,h=b.x,k=b.y,l=d;g<f;)if(g=Math.random(),g=0.5>g?-1*g:g,l=Math.atan2(c.y-k,c.x-h),h+=this.Lopt.part*Math.cos(l),k+=this.Lopt.part*Math.sin(l),0.8>g&&(l=d+g,h+=this.Lopt.part*Math.cos(l),k+=this.Lopt.part*Math.sin(l)),lineDist=
Math.sqrt((h-c.x)*(h-c.x)+(k-c.y)*(k-c.y)),g=f-lineDist,this.canvas.lineTo(h,k),this.canvas.moveTo(h,k),this.canvas.stroke(),lineDist<this.Lopt.lastDist){this.makeLine({x:h,y:k},c);return}this.canvas.stroke();this.canvas.closePath();this.canvas.restore()};BattleMage.cUtil.prototype.makeCircleLight=function(b,c){var d=0,f=0,g=0;do f=b.x+c*Math.cos(d),g=b.y+c*Math.sin(d),this.makeLight(b,{x:f,y:g}),d+=6*Math.PI/100;while(6.1>=d)};Sprite=JAK.ClassMaker.makeClass({NAME:"Sprite",VERSION:"1.0"});
Sprite.prototype.$constructor=function(b,c,d){this.opt=d||{};this.canvas=b;this.img=c;this.start=this.opt.start;this.interval=this.opt.interval;this.step=this.interval/this.opt.steps;this.stepw=this.opt.step;this.direction=d.direction||RPG.S;this.scale=this.opt.scale||1};
Sprite.prototype.draw=function(b){var c=this.opt[this.direction].top,d=this.opt[this.direction].height,f=(new Date).getTime()-this.start,f=Math.floor(f/this.interval)%this.opt.steps;"step"in this.opt[this.direction]&&(this.stepw=this.opt[this.direction].step);var f=f*this.stepw,g=this.stepw*this.opt.scale,h=d*this.opt.scale;this.img&&("left"in this.opt[this.direction]&&(f+=this.opt[this.direction].left),this.canvas.drawImage(this.img,f,c,this.stepw,d,b.x,b.y,g,h))};var Stats=function(){var b,c,d=0,f=0,g=Date.now(),h=g,k=g,l=0,o=1E3,p=0,n,q,t,r=[[16,16,48],[0,255,255]],z=0,F=1E3,G=0,w,j,x,v=[[16,48,16],[0,255,0]];b=document.createElement("div");b.style.cursor="pointer";b.style.width="80px";b.style.opacity="0.9";b.style.zIndex="10001";b.addEventListener("mousedown",function(b){b.preventDefault();d=(d+1)%2;0==d?(n.style.display="block",w.style.display="none"):(n.style.display="none",w.style.display="block")},!1);n=document.createElement("div");n.style.textAlign=
"left";n.style.lineHeight="1.2em";n.style.backgroundColor="rgb("+Math.floor(r[0][0]/2)+","+Math.floor(r[0][1]/2)+","+Math.floor(r[0][2]/2)+")";n.style.padding="0 0 3px 3px";b.appendChild(n);q=document.createElement("div");q.style.fontFamily="Helvetica, Arial, sans-serif";q.style.fontSize="9px";q.style.color="rgb("+r[1][0]+","+r[1][1]+","+r[1][2]+")";q.style.fontWeight="bold";q.innerHTML="FPS";n.appendChild(q);t=document.createElement("div");t.style.position="relative";t.style.width="74px";t.style.height=
"30px";t.style.backgroundColor="rgb("+r[1][0]+","+r[1][1]+","+r[1][2]+")";for(n.appendChild(t);74>t.children.length;)c=document.createElement("span"),c.style.width="1px",c.style.height="30px",c.style.cssFloat="left",c.style.backgroundColor="rgb("+r[0][0]+","+r[0][1]+","+r[0][2]+")",t.appendChild(c);w=document.createElement("div");w.style.textAlign="left";w.style.lineHeight="1.2em";w.style.backgroundColor="rgb("+Math.floor(v[0][0]/2)+","+Math.floor(v[0][1]/2)+","+Math.floor(v[0][2]/2)+")";w.style.padding=
"0 0 3px 3px";w.style.display="none";b.appendChild(w);j=document.createElement("div");j.style.fontFamily="Helvetica, Arial, sans-serif";j.style.fontSize="9px";j.style.color="rgb("+v[1][0]+","+v[1][1]+","+v[1][2]+")";j.style.fontWeight="bold";j.innerHTML="MS";w.appendChild(j);x=document.createElement("div");x.style.position="relative";x.style.width="74px";x.style.height="30px";x.style.backgroundColor="rgb("+v[1][0]+","+v[1][1]+","+v[1][2]+")";for(w.appendChild(x);74>x.children.length;)c=document.createElement("span"),
c.style.width="1px",c.style.height=30*Math.random()+"px",c.style.cssFloat="left",c.style.backgroundColor="rgb("+v[0][0]+","+v[0][1]+","+v[0][2]+")",x.appendChild(c);return{getDomElement:function(){return b},getFps:function(){return l},getFpsMin:function(){return o},getFpsMax:function(){return p},getMs:function(){return z},getMsMin:function(){return F},getMsMax:function(){return G},update:function(){g=Date.now();z=g-h;F=Math.min(F,z);G=Math.max(G,z);j.textContent=z+" MS ("+F+"-"+G+")";var b=Math.min(30,
30-30*(z/200));x.appendChild(x.firstChild).style.height=b+"px";h=g;f++;g>k+1E3&&(l=Math.round(1E3*f/(g-k)),o=Math.min(o,l),p=Math.max(p,l),q.textContent=l+" FPS ("+o+"-"+p+")",b=Math.min(30,30-30*(l/100)),t.appendChild(t.firstChild).style.height=b+"px",k=g,f=0)}}};RPGMAP.ImageMap=JAK.ClassMaker.makeClass({NAME:"RPGMAP.ImageMap",VERSION:"1.1",EXTEND:RPGMAP,EXTEND:RPGMAP.ShadowLighting});RPGMAP.ImageMap.prototype._obsticlesFinder=function(b){if(!b)return"#000";var c="#000";switch(this.MAP[b[0]][b[1]]){case RPG.WALL:c="#a30000";break;case RPG.NONE:c="#272727";break;case RPG.YOU:c="#fff";break;case RPG.END:c="#0000cc";break;default:c="#272727"}return c};RPGMAP.ImageMap.prototype.build=function(){this._imageLoad()};
RPGMAP.ImageMap.prototype._imageLoad=function(){for(i in RPG.STYLE)if(!RPG.STYLE[i].loaded){var b=JAK.mel("img");b.src=RPG.STYLE[i].img;RPG.STYLE[i].loaded=1;RPG.STYLE[i].img=b;this.ec.push(JAK.Events.addListener(b,"load",this,"_imageLoad"));return}this.opt.canvas?(this.canvasBuild=1,this.buildCanvas()):(this.htmlBuild=1,this.buildHtml())};
RPGMAP.ImageMap.prototype._bigRebuild=function(b){for(var c=0;c<this.MAP.length;c++)for(var d=0;d<this.MAP[c].length;d++){var f=RPG.STYLE[this.MAP[c][d]].img,g=d*this.opt.pointSize.w,h=c*this.opt.pointSize.h;b[[c,d].toString()]?this.canvasMap.drawImage(f,g,h,this.opt.pointSize.w,this.opt.pointSize.h):this._drawNothing({x:g,y:h},[c,d],f)}};
RPGMAP.ImageMap.prototype._smallRebuild=function(b){var c=2*this.opt.radius*this.pointW+this.pointW,d=this._smallCorner(),f=d.x,g=d.y;this.smallStart=d;for(var h=f+c+this.pointW>this.MAP[0].length*this.pointW?this.MAP[0].length*this.pointW:f+c+this.pointW,k=g+c+this.pointH>this.MAP.length*this.pointH?this.MAP.length*this.pointH:g+c+this.pointH,c=f%(1*this.pointW),d=g%(1*this.pointH),h=Math.floor(h/this.opt.pointSize.w)>this.MAP[0].length?this.MAP[0].length:Math.floor(h/this.opt.pointSize.w),k=Math.floor(k/
this.opt.pointSize.h)>this.MAP.length?this.MAP.length:Math.floor(k/this.opt.pointSize.h),f=Math.floor(f/this.opt.pointSize.w)>this.MAP[0].length?this.MAP[0].length:Math.floor(f/this.opt.pointSize.w),l=0,g=Math.floor(g/this.opt.pointSize.h)>this.MAP.length?this.MAP.length:Math.floor(g/this.opt.pointSize.h);g<k;g++){for(var o=0,p=f;p<h;p++){var n=this.MAP[g][p],q=0;if(b[[g,p].toString()])switch(n){case RPG.WALL:RPG.STYLE[RPG.WALL]&&(q=1);break;case RPG.NONE:RPG.STYLE[RPG.NONE]&&(q=1)}var t=this.pointW*
o-c,r=this.pointH*l-d;q?(n=RPG.STYLE[n].img,this.canvasMap.drawImage(n,t,r,this.opt.pointSize.w,this.opt.pointSize.h)):(n=RPG.STYLE[n].img,this._drawNothing({x:t,y:r},[g,p],n));o+=1}l+=1}};RPGMAP.ImageMap.prototype._drawNothing=function(b,c,d){var f=!0;this.opt.visibility&&(this._coordsInVisible(c)||(f=!1));f&&(c=d||RPG.STYLE[RPG.NONE].img,this.canvasMap.save(),this.canvasMap.globalAlpha=0.6,this.canvasMap.drawImage(c,b.x,b.y,this.opt.pointSize.w,this.opt.pointSize.h),this.canvasMap.restore())};JAK.Timekeeper=JAK.ClassMaker.makeSingleton({NAME:"JAK.Timekeeper",VERSION:"1.1"});JAK.Timekeeper.prototype.$constructor=function(){this._delay=1E3/60;this._listeners=[];this._running=0;this._tick=this._tick.bind(this);this._scheduler=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(b){setTimeout(b,this._delay)}};
JAK.Timekeeper.prototype.addListener=function(b,c,d){if(-1!=this._findListener(b))throw Error("This listener is already attached");b={what:b,method:c,count:d||1,bucket:0};b.bucket=b.count;this._listeners.push(b);2!=this._running&&(0==this._running&&this._schedule(),this._running=2);return this};
JAK.Timekeeper.prototype.removeListener=function(b){b=this._findListener(b);if(-1==b)throw Error("Cannot find listener to be removed");this._listeners.splice(b,1);this._listeners.length||(this._running=1);return this};JAK.Timekeeper.prototype._findListener=function(b){for(var c=0;c<this._listeners.length;c++)if(this._listeners[c].what==b)return c;return-1};
JAK.Timekeeper.prototype._tick=function(){1==this._running&&(this._running=0);if(0!=this._running){this._schedule();for(var b=0;b<this._listeners.length;b++){var c=this._listeners[b];c.bucket--;if(!c.bucket){c.bucket=c.count;var d=c.what;("string"==typeof c.method?d[c.method]:c.method).call(d)}}}};JAK.Timekeeper.prototype._schedule=function(){var b=this._scheduler;b(this._tick,null)};Particle=JAK.ClassMaker.makeClass({VERSION:"1.0",NAME:"Particle"});Particle.circleOpt={};Particle.timekeeper=null;Particle.particles=[];
Particle.prototype.$constructor=function(b){this.opt={angle:0,speed:0,posX:0,posY:0,velX:0,velY:0,size:1,maxSize:1,alpha:0.2,gravity:0,shrink:1,fade:0,life:1E3,rotate:!1,img:null,canvas:null,rect:!1,arc:!1,sprites:!1};for(var c in b)this.opt[c]=b[c];this.startTime=(new Date).getTime();this.posX=this.opt.posX+numRange(-1*this.opt.velX,this.opt.velX);this.posY=this.opt.posY+numRange(-1*this.opt.velY,this.opt.velY);this.opt.sprites&&(this.sprite=new Sprite(this.opt.canvas,SPRITE.img,SPRITE));b=this.posX+
this.opt.speed*Math.cos(this.opt.angle);c=this.posY+this.opt.speed*Math.sin(this.opt.angle);this.opt.rotate=!1!==this.opt.rotate?this.opt.rotate:0;this.rotate=0;this.rad=Math.PI/180;this.x=b-this.posX;this.y=c-this.posY};Particle.prototype.$destructor=function(){for(var b in this)this[b]=null};
Particle.prototype.update=function(){if(-1*(this.startTime-(new Date).getTime())>=this.opt.life)this.$destructor();else if(this.posX+=this.x,this.posY+=this.y,this.posY+=this.opt.gravity,this.rotate+=this.opt.rotate*this.rad,this.opt.size*=this.opt.shrink,0<this.opt.maxSize&&this.opt.size>this.opt.maxSize&&(this.opt.size=this.opt.maxSize),this.opt.alpha-=this.opt.fade,0>this.opt.alpha&&(this.opt.alpha=0),!0===this.opt.rotate)this.rotate=this.opt.angle+2*Math.PI/60};
Particle.prototype._drawRect=function(){var b=this.opt.canvas,c=50*this.opt.size,d=50*this.opt.size;b.translate(this.posX,this.posY);b.rotate(this.rotate);b.translate(-1*(c/2),-1*(d/2));b.fillStyle="#fff";b.fillRect(0,0,c,d);b.restore()};
Particle.prototype._drawArc=function(){var b=this.opt.canvas;b.beginPath();b.strokeStyle="#fff";b.lineWidth=1;b.globalAlpha=this.opt.alpha;var c=50*this.opt.size,d=50*this.opt.size;b.translate(this.posX,this.posY);this.opt.rotate&&b.rotate(this.rotate);b.translate(-1*(c/2),-1*(d/2));b.arc(0,0,c,0,2*Math.PI,!0);b.stroke()};Particle.prototype._drawSprites=function(){this.sprite.draw({x:this.posX,y:this.posY})};
Particle.prototype.draw=function(){var b=this.opt.canvas;b.save();b.globalAlpha=this.opt.alpha;var c=this.opt.img.width*this.opt.size,d=this.opt.img.height*this.opt.size,f=this.posX,g=this.posY;!0===this.opt.rect?this._drawRect():!0===this.opt.arc?this._drawArc():!0===this.opt.sprites?this._drawSprites():(b.translate(f,g),this.opt.rotate&&b.rotate(this.rotate),b.translate(-1*(c/2),-1*(d/2)),b.drawImage(this.opt.img,0,0,c,d));b.restore()};
Particle.setOptions=function(b){this.circleOpt=b;this.timekeeper||(this.timekeeper=JAK.Timekeeper.getInstance(),this.timekeeper.addListener(this,"circleTick",2))};Particle.circleTick=function(){var b=this.circleOpt;b.angle=0;for(b.speed=20;6.3>b.angle;)b.angle+=0.2,this.particles.push(new this(b));b.canvas.clearRect(0,0,b.canvas.width,b.canvas.height);for(b=0;b<this.particles.length;b++)this.particles[b].draw(),this.particles[b].update();for(;500<this.particles.length;)this.particles.shift()};
function numRange(b,c){return Math.random()*(c-b)+b};var ImageLoader=JAK.ClassMaker.makeClass({NAME:"ImageLoader",VERSION:"1.0",IMPLEMENT:JAK.ISignals});ImageLoader.prototype.$constructor=function(b,c){this.callback=c||null;this.counter=this.error=0;this.images=b||[];this.img=new Image;this.dom={};this._buildLoader();this.loadEvent=JAK.Events.addListener(this.img,"load",this,"_loaded");this.errorEvent=JAK.Events.addListener(this.img,"error",this,"_errored");this.img.src=this.images[this.counter]};
ImageLoader.prototype._buildLoader=function(){this.dom.root=JAK.mel("div",{className:"ImageLoader"});document.body.appendChild(this.dom.root)};ImageLoader.prototype._write=function(b){this.dom.root.innerHTML+="<p>"+b+"</p>"};
ImageLoader.prototype._loaded=function(){this._write("<strong>"+(this.counter+1)+".</strong> <i>"+this.images[this.counter]+"</i> ......................... loaded");this.counter++;this.counter>=this.images.length?(this._done(),this.makeEvent("images-loadded",{error:this.error})):this.img.src=this.images[this.counter]};
ImageLoader.prototype._errored=function(){this.error=1;this._write("<strong>"+(this.counter+1)+".</strong> <i>"+this.images[this.counter]+"</i> ......................... ERROR");this.counter++;this.counter>=this.images.length?(this.makeEvent("images-loaded",{error:this.error}),this._done()):this.img.src=this.images[this.counter]};ImageLoader.prototype._done=function(){this.callback&&this.callback(this.error?!1:!0)};ImageLoader.prototype.hide=function(){this.dom.root.parentNode.removeChild(this.dom.root)};RPGMAP=JAK.ClassMaker.makeClass({NAME:"RPGMAP",VERSION:"1.0",IMPLEMENT:JAK.ISignals});RPGMAP.prototype.$constructor=function(b,c){this.ec=[];this.opt={pointSize:{w:50,h:50},mapElm:null,canvas:null,radius:10,visibility:!1,allMap:1};for(i in b)this.opt[i]=b[i];this.visibleCoords=[];this.oldCoordsStart=[];this.coordsStart=[];this.objectMap=this._buildConstantObjects(c);this.MAP=c||[];this.dom={};this.dom.map=JAK.gel(this.opt.mapElm);this.radius=this.opt.radius};
RPGMAP.prototype.getMapSize=function(){this.mapSize||(this.mapSize={w:this.opt.pointSize.w*2*this.opt.radius+this.opt.pointSize.w,h:this.opt.pointSize.h*2*this.opt.radius+this.opt.pointSize.h});return this.mapSize};RPGMAP.prototype._buildConstantObjects=function(b){for(var c=[],d=0;d<b.length;d++){for(var f=b[d],g=[],h=0;h<f.length;h++)g.push({cons:f[h],visited:!1});c.push(g)}return c};RPGMAP.prototype.build=function(){this.opt.canvas?(this.canvasBuild=1,this.buildCanvas()):(this.htmlBuild=1,this.buildHtml())};
RPGMAP.prototype.buildHtml=function(){this.dom.map.style.position="relative";this.mapWidth=this.opt.pointSize.w*this.MAP[0].length;this.mapHeight=this.opt.pointSize.h*this.MAP.length;this.dom.map.style.width=this.mapWidth+"px";this.dom.map.style.height=this.mapHeight+"px";if(this.opt.allMap)for(var b=this.MAP,c=0;c<b.length;c++)for(var d=0;d<b[c].length;d++)this.dom.map.appendChild(JAK.mel("div",{},{position:"absolute",width:this.opt.pointSize.w+"px",height:this.opt.pointSize.h+"px",backgroundColor:RPG.STYLE[b[c][d]].color,
border:"1px solid #FFF",top:c*this.opt.pointSize.h+"px",left:d*this.opt.pointSize.w+"px"}));else this.dom.map.style.width=(2*this.radius+1)*this.opt.pointSize.w+"px",this.dom.map.style.height=(2*this.radius+1)*this.opt.pointSize.h+"px",this.dom.map.style.overflow="hidden",this._smallBuild()};RPGMAP.prototype._smallBuild=function(){this._fullscreen();this._smallRebuild(this._makeObjectFromVisibleCoords(this.showShadow()))};RPGMAP.prototype._bigBuild=function(){this._bigRebuild(this._makeObjectFromVisibleCoords(this.showShadow()))};
RPGMAP.prototype.buildCanvas=function(){this.dom.canvas=JAK.mel("canvas");if(this.opt.allMap){var b={w:this.MAP[0].length*this.opt.pointSize.w,h:this.MAP.length*this.opt.pointSize.h};this.mapWidth=b.w;this.mapHeight=b.h;this.canvasSize=b;this.dom.canvas.width=this.canvasSize.w;this.dom.canvas.height=this.canvasSize.h}else b={w:(2*this.radius+1)*this.opt.pointSize.w,h:(2*this.radius+1)*this.opt.pointSize.h},this.dom.canvas.width=b.w,this.dom.canvas.height=b.h,this.mapWidth=b.w,this.mapHeight=b.h;this.dom.map.appendChild(this.dom.canvas);
this.canvasMap=this.dom.canvas.getContext("2d");this.opt.allMap?this._bigBuild():this._smallBuild();this.makeEvent("map-loaded")};RPGMAP.prototype.getDomCanvas=function(){return this.dom.canvas};RPGMAP.prototype.getCanvas=function(){return this.canvasMap};RPGMAP.prototype._fullscreen=function(){this.pointW=this.opt.pointSize.w;this.pointH=this.opt.pointSize.h;this.smallStart=this._smallCorner()};RPGMAP.prototype.getStart=function(){return this.start};
RPGMAP.prototype.getCoords=function(b){return b?[Math.floor(b.y/this.opt.pointSize.h),Math.floor(b.x/this.opt.pointSize.w)]:this.coordsStart};RPGMAP.prototype.getMap=function(){return this.MAP};RPGMAP.prototype.getPointSize=function(){return this.opt.pointSize};RPGMAP.prototype._randRange=function(b,c){return-1*(Math.floor(Math.random()*(b-c+1))+b)};
RPGMAP.prototype._obsticlesFinder=function(b){if(!b)return"#000";var c="#000";switch(this.MAP[b[0]][b[1]]){case RPG.WALL:c="#a30000";break;case RPG.NONE:c="#272727";break;case RPG.YOU:c="#fff";break;case RPG.END:c="#0000cc";break;default:c="#272727"}return c};RPGMAP.prototype._clearMap=function(){this.canvasBuild&&this.canvasMap.clearRect(0,0,this.mapWidth,this.mapHeight);this.htmlBuild&&JAK.DOM.clear(this.dom.map)};
RPGMAP.prototype._smallCorner=function(){var b=(2*this.opt.radius*this.pointW+this.pointW-this.pointW)/2,c=this.start[0],d=this.start[1];return{x:0>c-b?0:c-b,y:0>d-b?0:d-b}};
RPGMAP.prototype._smallRebuild=function(b){var c=2*this.opt.radius*this.pointW+this.pointW,d=this._smallCorner(),f=d.x,g=d.y;this.smallStart=d;for(var h=f+c+this.pointW>this.MAP.length*this.pointW?this.MAP.length*this.pointW:f+c+this.pointW,k=g+c+this.pointH>this.MAP[0].length*this.pointH?this.MAP[0].length*this.pointH:g+c+this.pointH,c=f%(1*this.pointW),d=g%(1*this.pointH),h=Math.floor(h/this.pointW)>this.MAP.length?this.MAP.length:Math.floor(h/this.pointW),k=Math.floor(k/this.pointH)>this.MAP[0].length?
this.MAP[0].length:Math.floor(k/this.pointH),f=Math.floor(f/this.pointW)>this.MAP.length?this.MAP.length:Math.floor(f/this.pointW),l=0,g=Math.floor(g/this.pointH)>this.MAP[0].length?this.MAP[0].length:Math.floor(g/this.pointH);g<k;g++){for(var o=0,p=f;p<h;p++){var n=b[[g,p].toString()]?1:0,q="#000",t=this.pointW*o-c,r=this.pointH*l-d;this.htmlBuild&&n?this.dom.map.appendChild(JAK.mel("div",{},{position:"absolute",width:this.pointW+"px",height:this.pointH+"px",backgroundColor:RPG.STYLE[this.MAP[g][p]].color,
top:r+"px",left:t+"px"})):n&&(q=RPG.STYLE[this.MAP[g][p]].color,this.canvasMap.fillStyle=q,this.canvasMap.fillRect(t,r,this.pointW,this.pointH));o+=1}l+=1}};RPGMAP.prototype.fillSingleSquare=function(b,c){this.canvasMap.fillStyle=c;this.canvasMap.fillRect(this.pointW*b[0],this.pointH*b[1],this.pointW,this.pointH)};RPGMAP.prototype._makeObjectFromVisibleCoords=function(b){for(var c={},d=0;d<b.length;d++)c[b[d].toString()]=1;return c};RPGMAP.prototype.draw=function(){this._rebuildMap()};
RPGMAP.prototype._rebuildMap=function(){this._clearMap();var b=this.showShadow(),c=this._makeObjectFromVisibleCoords(b);this.opt.visibility&&this._visibleControl(b);this.opt.allMap?this._bigRebuild(c):this._smallRebuild(c);this.makeEvent("rebuildMap")};RPGMAP.prototype._visibleControl=function(b){for(var c=0;c<b.length;c++){var d=b[c],d=this.objectMap[d[0]][d[1]];d.visited||(d.visited=!0)}};RPGMAP.prototype._coordsInVisible=function(b){return this.objectMap[b[0]][b[1]].visited};
RPGMAP.prototype._bigRebuild=function(){for(var b=0;b<a.length;b++)if(a[b]){var c=a[b][0],d=a[b][1],f="#000";switch(this.MAP[c][d]){case RPG.WALL:f="#a30000";break;case RPG.NONE:f="#272727";break;case RPG.YOU:f="#fff";break;case RPG.NPC:f="#00FF00";break;case RPG.END:f="#0000cc";break;default:return}this.canvasMap.fillStyle=f;this.canvasMap.fillRect(this.pointW*c,this.pointH*d,this.pointW,this.pointH)}};RPGMAP.prototype.showShadow=function(){return 0};
RPGMAP.prototype.update=function(){if(this.opt.allMap){if(this.oldCoordsStart[0]!=this.coordsStart[0]||this.oldCoordsStart[1]!=this.coordsStart[1]||1>this.oldCoordsStart.length)this.draw(),this.oldCoordsStart=[],this.oldCoordsStart.push(this.coordsStart[0]),this.oldCoordsStart.push(this.coordsStart[1])}else this.draw()};
RPGMAP.prototype.setMidPoint=function(b){this.start=[b.x,b.y];this.coordsStart=[Math.floor(b.y/this.opt.pointSize.h),Math.floor(b.x/this.opt.pointSize.w)];this._fullscreen();this.smallStart=this._smallCorner()};function Stick(b,c){this.active=c;this.atLimit=!1;this.length=1;this.maxLength=b;this.limit={x:0,y:0};this.input={x:0,y:0}}Stick.prototype.getRadians=function(b,c){return Math.atan2(b,-c)};Stick.prototype.getVectorFromRadians=function(b,c){c=Number(c)||1;return{x:Math.sin(b)*c,y:-Math.cos(b)*c}};Stick.prototype.getVectorLength=function(b){return Math.sqrt(b.x*b.x+b.y*b.y)};Stick.prototype.getVectorNormal=function(b){var c=this.getVectorLength(b);return 0===c?b:{x:b.x*(1/c),y:b.y*(1/c)}};
Stick.prototype.setLimitXY=function(b,c){this.limit={x:b,y:c}};Stick.prototype.setInputXY=function(b,c){this.input={x:b,y:c}};Stick.prototype.subtractVectors=function(b,c){return{x:b.x-c.x,y:b.y-c.y}};
Stick.prototype.update=function(){var b=this.subtractVectors(this.input,this.limit),c=this.getVectorLength(b);if(Math.round(c)>=this.maxLength){var c=this.maxLength,d=this.getRadians(b.x,b.y);this.atLimit=!0;this.input=this.getVectorFromRadians(d,c);this.input.x+=this.limit.x;this.input.y+=this.limit.y}else this.atLimit=!1;this.length=c;this.normal=this.getVectorNormal(b)};(function(b,c){function d(b){return this.clearStack(b)}var f={identity:[1,0,0,0,1,0,0,0,1],multiply:function(b,c){var d=b[0],f=b[1],g=b[2],h=b[3],k=b[4],j=b[5],l=b[6],n=b[7],o=b[8],p=c[0],D=c[1],E=c[2],A=c[3],m=c[4],y=c[5],B=c[6],u=c[7],C=c[8];c[0]=p*d+A*f+B*g;c[1]=D*d+m*f+u*g;c[2]=E*d+y*f+C*g;c[3]=p*h+A*k+B*j;c[4]=D*h+m*k+u*j;c[5]=E*h+y*k+C*j;c[6]=p*l+A*n+B*o;c[7]=D*l+m*n+u*o;c[8]=E*l+y*n+C*o},vec2_multiply:function(b,c){var d=[];d[0]=c[0]*b[0]+c[3]*b[1]+c[6];d[1]=c[1]*b[0]+c[4]*b[1]+c[7];return d},
transpose:function(b){return[b[0],b[3],b[6],b[1],b[4],b[7],b[2],b[5],b[8]]}};d.prototype.clearStack=function(b){this.m_stack=[];this.m_cache=[];this.valid=this.c_stack=0;this.result=null;for(var d=0;16>d;d++)this.m_stack[d]=this.getIdentity();b!==c?this.m_stack[0]=b:this.setIdentity()};d.prototype.setIdentity=function(){this.m_stack[this.c_stack]=this.getIdentity();this.valid===this.c_stack&&this.c_stack&&this.valid--};d.prototype.getIdentity=function(){return[1,0,0,0,1,0,0,0,1]};d.prototype.getResult=
function(){if(!this.c_stack)return this.m_stack[0];var b=f.identity;this.valid>this.c_stack-1&&(this.valid=this.c_stack-1);for(var c=this.valid;c<this.c_stack+1;c++)b=f.multiply(this.m_stack[c],b),this.m_cache[c]=b;this.valid=this.c_stack-1;return this.result=this.m_cache[this.c_stack]};d.prototype.pushMatrix=function(){this.c_stack++;this.m_stack[this.c_stack]=this.getIdentity()};d.prototype.popMatrix=function(){0!==this.c_stack&&this.c_stack--};var g=d.prototype.getIdentity();d.prototype.translate=
function(b,c){g[6]=b;g[7]=c;f.multiply(g,this.m_stack[this.c_stack])};var h=d.prototype.getIdentity();d.prototype.scale=function(b,c){h[0]=b;h[4]=c;f.multiply(h,this.m_stack[this.c_stack])};var k=d.prototype.getIdentity();d.prototype.rotate=function(c){var d;d=b.sin(-c);c=b.cos(-c);k[0]=c;k[3]=d;k[1]=-d;k[4]=c;f.multiply(k,this.m_stack[this.c_stack])};var l=this.WebGL2D=function(b,f){this.canvas=b;this.options=f||{};this.shaderProgram=this.vs=this.fs=this.gl=c;this.transform=new d;this.shaderPool=
[];this.maxTextureSize=c;b.gl2d=this;b.$getContext=b.getContext;b.getContext=function(c){return function(d){if((c.options.force||"webgl-2d"===d)&&!(0===b.width||0===b.height)){if(c.gl)return c.gl;d=c.gl=c.canvas.$getContext("experimental-webgl");c.initShaders();c.initBuffers();c.initCanvas2DAPI();d.viewport(0,0,c.canvas.width,c.canvas.height);d.clearColor(1,1,1,1);d.clear(d.COLOR_BUFFER_BIT);d.colorMask(1,1,1,0);d.enable(d.BLEND);d.blendFunc(d.SRC_ALPHA,d.ONE_MINUS_SRC_ALPHA);c.maxTextureSize=d.getParameter(d.MAX_TEXTURE_SIZE);
return d}return c.canvas.$getContext(d)}}(this);this.postInit()};l.enable=function(b,c){return b.gl2d||new l(b,c)};l.prototype.getFragmentShaderSource=function(b){return["#ifdef GL_ES\nprecision highp float;\n#endif","#define hasTexture "+(b&1?"1":"0"),"#define hasCrop "+(b&2?"1":"0"),"varying vec4 vColor;\n#if hasTexture\nvarying vec2 vTextureCoord;\nuniform sampler2D uSampler;\n#if hasCrop\nuniform vec4 uCropSource;\n#endif\n#endif\nvoid main(void) {\n#if hasTexture\n#if hasCrop\ngl_FragColor = texture2D(uSampler, vec2(vTextureCoord.x * uCropSource.z, vTextureCoord.y * uCropSource.w) + uCropSource.xy);\n#else\ngl_FragColor = texture2D(uSampler, vTextureCoord);\n#endif\n#else\ngl_FragColor = vColor;\n#endif\n}"].join("\n")};
l.prototype.getVertexShaderSource=function(b,c){var d=2/this.canvas.width,f=-2/this.canvas.height,b=b||1;return["#define hasTexture "+(c&1?"1":"0"),"attribute vec4 aVertexPosition;\n#if hasTexture\nvarying vec2 vTextureCoord;\n#endif\nuniform vec4 uColor;","uniform mat3 uTransforms["+b+"];","varying vec4 vColor;","const mat4 pMatrix = mat4("+d+",0,0,0, 0,"+f+",0,0, 0,0,1.0,1.0, -1.0,1.0,0,0);","mat3 crunchStack(void) {\nmat3 result = uTransforms[0];","for (int i = 1; i < "+b+"; ++i) {","result = uTransforms[i] * result;\n}\nreturn result;\n}\nvoid main(void) {\nvec3 position = crunchStack() * vec3(aVertexPosition.x, aVertexPosition.y, 1.0);\ngl_Position = pMatrix * vec4(position, 1.0);\nvColor = uColor;\n#if hasTexture\nvTextureCoord = aVertexPosition.zw;\n#endif\n}"].join("\n")};
l.prototype.initShaders=function(b,c){var d=this.gl,b=b||1,c=c||0,f=this.shaderPool[b];f||(f=this.shaderPool[b]=[]);if(f=f[c])return d.useProgram(f),this.shaderProgram=f;var g=this.fs=d.createShader(d.FRAGMENT_SHADER);d.shaderSource(this.fs,this.getFragmentShaderSource(c));d.compileShader(this.fs);if(!d.getShaderParameter(this.fs,d.COMPILE_STATUS))throw"fragment shader error: "+d.getShaderInfoLog(this.fs);var h=this.vs=d.createShader(d.VERTEX_SHADER);d.shaderSource(this.vs,this.getVertexShaderSource(b,
c));d.compileShader(this.vs);if(!d.getShaderParameter(this.vs,d.COMPILE_STATUS))throw"vertex shader error: "+d.getShaderInfoLog(this.vs);f=this.shaderProgram=d.createProgram();f.stackDepth=b;d.attachShader(f,g);d.attachShader(f,h);d.linkProgram(f);if(!d.getProgramParameter(f,d.LINK_STATUS))throw"Could not initialise shaders.";d.useProgram(f);f.vertexPositionAttribute=d.getAttribLocation(f,"aVertexPosition");d.enableVertexAttribArray(f.vertexPositionAttribute);f.uColor=d.getUniformLocation(f,"uColor");
f.uSampler=d.getUniformLocation(f,"uSampler");f.uCropSource=d.getUniformLocation(f,"uCropSource");f.uTransforms=[];for(g=0;g<b;++g)f.uTransforms[g]=d.getUniformLocation(f,"uTransforms["+g+"]");return this.shaderPool[b][c]=f};var o,p,n=new Float32Array([0,0,0,0,0,1,0,1,1,1,1,1,1,0,1,0]);l.prototype.initBuffers=function(){var b=this.gl;o=b.createBuffer();b.createBuffer();p=b.createBuffer();b.createBuffer();b.bindBuffer(b.ARRAY_BUFFER,o);b.bufferData(b.ARRAY_BUFFER,n,b.STATIC_DRAW)};l.instances=[];l.prototype.postInit=
function(){l.instances.push(this)};l.prototype.initCanvas2DAPI=function(){function b(c,d,f,g){function h(b){return 1>6*b?j+6*(k-j)*b:1>2*b?k:2>3*b?j+6*(k-j)*(2/3-b):j}var j,k,c=(c%360+360)%360/360,d=100<d?1:d/100,d=0>d?0:d,f=100<f?1:f/100,f=0>f?0:f;k=0.5>=f?f*(d+1):f+d-f*d;j=2*f-k;d=h(c+1/3);f=h(c);c=h(c-1/3);return[d,f,c,g]}function c(d){var f=[],g,h,j,k,l;if(g=I.exec(d)){j=g[1];k=parseFloat(g[8]);if(j&&isNaN(k)||!j&&!isNaN(k))return!1;l=g[3];for(var m=2;8>m;m+=2){d=g[m];h=g[m+1];if(h!==l)return!1;
d=h?100<d?1:d/100:255<d?1:d/255;d=0>d?0:d;f.push(d)}f.push(j?k:1)}else if(g=J.exec(d))j=g[1],k=parseFloat(g[5]),f=b(g[2],g[3],g[4],parseFloat(j&&k?k:1));else if(g=D.exec(d))f=parseInt(g[1],16),f=[((f&16711680)>>16)/255,((f&65280)>>8)/255,(f&255)/255,1];else if(g=E.exec(d))f="#"+[g[1],g[1],g[2],g[2],g[3],g[3]].join(""),f=c(f);else if(d.toLowerCase()in A)f=c(A[d.toLowerCase()]);else if("transparent"===d.toLowerCase())f=[0,0,0,0];else return!1;return f}function d(b){return"rgba("+255*b[0]+", "+255*b[1]+
", "+255*b[2]+", "+parseFloat(b[3])+")"}function f(b){for(var c=k.transform.m_stack,d=0,g=k.transform.c_stack+1;d<g;++d)j.uniformMatrix3fv(b.uTransforms[d],!1,c[g-1-d])}function g(b,c){this.closed=!1;this.verts=[b,c,0,0]}function h(b){this.obj=j.createTexture();this.index=H.push(this);C.push(b);if(b.width>k.maxTextureSize||b.height>k.maxTextureSize){var c=document.createElement("canvas");c.width=b.width>k.maxTextureSize?k.maxTextureSize:b.width;c.height=b.height>k.maxTextureSize?k.maxTextureSize:
b.height;c.getContext("2d").drawImage(b,0,0,b.width,b.height,0,0,c.width,c.height);b=c}j.bindTexture(j.TEXTURE_2D,this.obj);j.texImage2D(j.TEXTURE_2D,0,j.RGBA,j.RGBA,j.UNSIGNED_BYTE,b);j.texParameteri(j.TEXTURE_2D,j.TEXTURE_WRAP_S,j.CLAMP_TO_EDGE);j.texParameteri(j.TEXTURE_2D,j.TEXTURE_WRAP_T,j.CLAMP_TO_EDGE);j.texParameteri(j.TEXTURE_2D,j.TEXTURE_MAG_FILTER,j.LINEAR);0<b.width&&0===(b.width-1&b.width)&&0<b.height&&0===(b.height-1&b.height)?(j.texParameteri(j.TEXTURE_2D,j.TEXTURE_MIN_FILTER,j.LINEAR_MIPMAP_LINEAR),
j.generateMipmap(j.TEXTURE_2D)):j.texParameteri(j.TEXTURE_2D,j.TEXTURE_MIN_FILTER,j.LINEAR);j.bindTexture(j.TEXTURE_2D,null)}var k=this,j=this.gl,l=document.createElement("canvas");l.width=k.canvas.width;l.height=k.canvas.height;var n=l.getContext("2d"),I=/^rgb(a)?\(\s*(-?[\d]+)(%)?\s*,\s*(-?[\d]+)(%)?\s*,\s*(-?[\d]+)(%)?\s*,?\s*(-?[\d\.]+)?\s*\)$/,J=/^hsl(a)?\(\s*(-?[\d\.]+)\s*,\s*(-?[\d\.]+)%\s*,\s*(-?[\d\.]+)%\s*,?\s*(-?[\d\.]+)?\s*\)$/,D=/^#([0-9A-Fa-f]{6})$/,E=/^#([0-9A-Fa-f])([0-9A-Fa-f])([0-9A-Fa-f])$/,
A={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",
darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",
greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",
lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",
orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",
snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},m={},y=[];m.fillStyle=[0,0,0,1];Object.defineProperty(j,"fillStyle",{get:function(){return d(m.fillStyle)},set:function(b){m.fillStyle=c(b)||m.fillStyle}});m.strokeStyle=[0,0,0,1];Object.defineProperty(j,"strokeStyle",{get:function(){return d(m.strokeStyle)},
set:function(b){m.strokeStyle=c(b)||drawStyle.strokeStyle}});j.$lineWidth=j.lineWidth;m.lineWidth=1;Object.defineProperty(j,"lineWidth",{get:function(){return m.lineWidth},set:function(b){j.$lineWidth(b);m.lineWidth=b}});m.lineCap="butt";Object.defineProperty(j,"lineCap",{get:function(){return m.lineCap},set:function(b){m.lineCap=b}});m.lineJoin="miter";Object.defineProperty(j,"lineJoin",{get:function(){return m.lineJoin},set:function(b){m.lineJoin=b}});m.miterLimit=10;Object.defineProperty(j,"miterLimit",
{get:function(){return m.miterLimit},set:function(b){m.miterLimit=b}});m.shadowOffsetX=0;Object.defineProperty(j,"shadowOffsetX",{get:function(){return m.shadowOffsetX},set:function(b){m.shadowOffsetX=b}});m.shadowOffsetY=0;Object.defineProperty(j,"shadowOffsetY",{get:function(){return m.shadowOffsetY},set:function(b){m.shadowOffsetY=b}});m.shadowBlur=0;Object.defineProperty(j,"shadowBlur",{get:function(){return m.shadowBlur},set:function(b){m.shadowBlur=b}});m.shadowColor="rgba(0, 0, 0, 0.0)";Object.defineProperty(j,
"shadowColor",{get:function(){return m.shadowColor},set:function(b){m.shadowColor=b}});m.font="10px sans-serif";Object.defineProperty(j,"font",{get:function(){return m.font},set:function(b){n.font=b;m.font=b}});m.textAlign="start";Object.defineProperty(j,"textAlign",{get:function(){return m.textAlign},set:function(b){m.textAlign=b}});m.textBaseline="alphabetic";Object.defineProperty(j,"textBaseline",{get:function(){return m.textBaseline},set:function(b){m.textBaseline=b}});m.globalAlpha=1;Object.defineProperty(j,
"globalAlpha",{get:function(){return m.globalAlpha},set:function(b){m.globalAlpha=b}});m.globalCompositeOperation="source-over";Object.defineProperty(j,"globalCompositeOperation",{get:function(){return m.globalCompositeOperation},set:function(b){m.globalCompositeOperation=b}});j.fillText=function(){};j.strokeText=function(){};j.measureText=function(){return 1};var B=document.createElement("canvas").getContext("2d");j.save=function(){k.transform.pushMatrix();y.push({fillStyle:[m.fillStyle[0],m.fillStyle[1],
m.fillStyle[2],m.fillStyle[3]],strokeStyle:[m.strokeStyle[0],m.strokeStyle[1],m.strokeStyle[2],m.strokeStyle[3]],globalAlpha:m.globalAlpha,globalCompositeOperation:m.globalCompositeOperation,lineCap:m.lineCap,lineJoin:m.lineJoin,lineWidth:m.lineWidth,miterLimit:m.miterLimit,shadowColor:m.shadowColor,shadowBlur:m.shadowBlur,shadowOffsetX:m.shadowOffsetX,shadowOffsetY:m.shadowOffsetY,textAlign:m.textAlign,font:m.font,textBaseline:m.textBaseline})};j.restore=function(){k.transform.popMatrix();y.length&&
(m=y.pop())};j.translate=function(b,c){k.transform.translate(b,c)};j.rotate=function(b){k.transform.rotate(b)};j.scale=function(b,c){k.transform.scale(b,c)};j.createImageData=function(b,c){return B.createImageData(b,c)};j.getImageData=function(b,c,d,f){var g=B.createImageData(d,f),h=new Uint8Array(4*d*f);j.readPixels(b,c,d,f,j.RGBA,j.UNSIGNED_BYTE,h);b=4*d;c=0;for(d=f/2;c<d;++c)for(var k=0,l=b;k<l;++k){var m=c*b+k,n=(f-c-1)*b+k;g.data[m]=h[n];g.data[n]=h[m]}return g};j.putImageData=function(b,c,d){j.drawImage(b,
c,d)};j.transform=function(b,c,d,f,g,h){var j=k.transform.m_stack[k.transform.c_stack];j[0]*=b;j[1]*=d;j[2]*=g;j[3]*=c;j[4]*=f;j[5]*=h;j[6]=0;j[7]=0};j.setTransform=function(b,c,d,f,g,h){k.transform.setIdentity();j.transform.apply(this,arguments)};j.fillRect=function(b,c,d,g){var h=k.transform,l=k.initShaders(h.c_stack+2,0);j.bindBuffer(j.ARRAY_BUFFER,o);j.vertexAttribPointer(l.vertexPositionAttribute,4,j.FLOAT,!1,0,0);h.pushMatrix();h.translate(b,c);h.scale(d,g);f(l);j.uniform4f(l.uColor,m.fillStyle[0],
m.fillStyle[1],m.fillStyle[2],m.fillStyle[3]);j.drawArrays(j.TRIANGLE_FAN,0,4);h.popMatrix()};j.strokeRect=function(b,c,d,g){var h=k.transform,l=k.initShaders(h.c_stack+2,0);j.bindBuffer(j.ARRAY_BUFFER,o);j.vertexAttribPointer(l.vertexPositionAttribute,4,j.FLOAT,!1,0,0);h.pushMatrix();h.translate(b,c);h.scale(d,g);f(l);j.uniform4f(l.uColor,m.strokeStyle[0],m.strokeStyle[1],m.strokeStyle[2],m.strokeStyle[3]);j.drawArrays(j.LINE_LOOP,0,4);h.popMatrix()};j.clearRect=function(){};var u=[];j.beginPath=
function(){u.length=0};j.closePath=function(){if(u.length){var b=u[u.length-1],c=b.verts[0],d=b.verts[1];b.closed=!0;b=new g(c,d);u.push(b)}};j.moveTo=function(b,c){u.push(new g(b,c))};j.lineTo=function(b,c){u.length?u[u.length-1].verts.push(b,c,0,0):j.moveTo(b,c)};j.quadraticCurveTo=function(){};j.bezierCurveTo=function(){};j.arcTo=function(){};j.rect=function(b,c,d,f){j.moveTo(b,c);j.lineTo(b+d,c);j.lineTo(b+d,c+f);j.lineTo(b,c+f);j.closePath()};j.arc=function(){};j.fill=function(){for(var b=0;b<
u.length;b++){var c=b,d=k.transform,g=k.initShaders(d.c_stack+2,0),c=u[c].verts;j.bindBuffer(j.ARRAY_BUFFER,p);j.bufferData(j.ARRAY_BUFFER,new Float32Array(c),j.STATIC_DRAW);j.vertexAttribPointer(g.vertexPositionAttribute,4,j.FLOAT,!1,0,0);d.pushMatrix();f(g);j.uniform4f(g.uColor,m.fillStyle[0],m.fillStyle[1],m.fillStyle[2],m.fillStyle[3]);j.drawArrays(j.TRIANGLE_FAN,0,c.length/4);d.popMatrix()}};j.stroke=function(){for(var b=0;b<u.length;b++){var c=b,d=k.transform,g=k.initShaders(d.c_stack+2,0),
c=u[c],h=c.verts;j.bindBuffer(j.ARRAY_BUFFER,p);j.bufferData(j.ARRAY_BUFFER,new Float32Array(h),j.STATIC_DRAW);j.vertexAttribPointer(g.vertexPositionAttribute,4,j.FLOAT,!1,0,0);d.pushMatrix();f(g);j.uniform4f(g.uColor,m.strokeStyle[0],m.strokeStyle[1],m.strokeStyle[2],m.strokeStyle[3]);c.closed?j.drawArrays(j.LINE_LOOP,0,h.length/4):j.drawArrays(j.LINE_STRIP,0,h.length/4);d.popMatrix()}};j.clip=function(){};j.isPointInPath=function(){};j.drawFocusRing=function(){};var C=[],H=[];j.drawImage=function(b,
c,d,g,l,m,n,p,q){var r=k.transform;r.pushMatrix();var t=1,u=!1;3===arguments.length?(r.translate(c,d),r.scale(b.width,b.height)):5===arguments.length?(r.translate(c,d),r.scale(g,l)):9===arguments.length&&(r.translate(m,n),r.scale(p,q),t|=2,u=!0);var t=k.initShaders(r.c_stack,t),v;v=C.indexOf(b);v=-1!==v?H[v]:new h(b);u&&j.uniform4f(t.uCropSource,c/b.width,d/b.height,g/b.width,l/b.height);j.bindBuffer(j.ARRAY_BUFFER,o);j.vertexAttribPointer(t.vertexPositionAttribute,4,j.FLOAT,!1,0,0);j.bindTexture(j.TEXTURE_2D,
v.obj);j.activeTexture(j.TEXTURE0);j.uniform1i(t.uSampler,0);f(t);j.drawArrays(j.TRIANGLE_FAN,0,4);r.popMatrix()}}})(Math);
